/// Soalan Kuiz Sejarah Tingkatan 2
/// Format: List<Map> untuk setiap Bab (Bab 1 hingga Bab 10)

const Map<String, List<Map<String, dynamic>>> sejarahKuizTingkatan2 = {
  'Bab 1': [
        {"soalan": "Apakah maksud Alam Melayu?", "pilihan": ["Kawasan yang ditadbir oleh penjajah Barat", "Wilayah yang berada di bawah kuasa raja Melayu", "Kawasan yang dihuni oleh bangsa Melayu dan menggunakan bahasa Melayu", "Tanah yang mempunyai hasil bumi yang kaya"], "jawapan": "Kawasan yang dihuni oleh bangsa Melayu dan menggunakan bahasa Melayu"},
        {"soalan": "Ciri utama Alam Melayu ialah...", "pilihan": ["Penggunaan bahasa Cina", "Kawasan tanah tinggi", "Kepelbagaian budaya", "Penggunaan bahasa Melayu sebagai bahasa pertuturan"], "jawapan": "Penggunaan bahasa Melayu sebagai bahasa pertuturan"},
        {"soalan": "Apakah kerajaan tertua dalam Alam Melayu?", "pilihan": ["Melaka", "Srivijaya", "Langkasuka", "Funan"], "jawapan": "Funan"},
        {"soalan": "Kerajaan Funan terletak di kawasan...", "pilihan": ["Selatan Vietnam", "Utara Thailand", "Sumatera", "Pantai timur Semenanjung Tanah Melayu"], "jawapan": "Selatan Vietnam"},
        {"soalan": "Siapakah pengasas kerajaan Champa?", "pilihan": ["Raja Rudravarman", "Fan Shih-man", "Che Bong Nga", "Raja Jayavarman II"], "jawapan": "Fan Shih-man"},
        {"soalan": "Apakah nama lain bagi kerajaan Kedah Tua?", "pilihan": ["Langkasuka", "Lembah Bujang", "Sungai Mas", "Pan Pan"], "jawapan": "Lembah Bujang"},
        {"soalan": "Kerajaan Srivijaya terkenal dengan peranan sebagai...", "pilihan": ["Pusat pertanian", "Pusat keagamaan Buddha", "Pusat pemerintahan tentera", "Pusat pentadbiran Barat"], "jawapan": "Pusat keagamaan Buddha"},
        {"soalan": "Apakah pelabuhan utama kerajaan Majapahit?", "pilihan": ["Tumasik", "Palembang", "Kampong Glam", "Tubang"], "jawapan": "Tumasik"},
        {"soalan": "Kerajaan Angkor diasaskan oleh...", "pilihan": ["Jayavarman II", "Suryavarman II", "Raja Indravarman", "Che Bong Nga"], "jawapan": "Jayavarman II"},
        {"soalan": "Apakah agama utama dalam Kerajaan Angkor?", "pilihan": ["Islam", "Buddha", "Kristian", "Hindu"], "jawapan": "Hindu"},
        {"soalan": "Apakah hasil utama kerajaan Alam Melayu?", "pilihan": ["Elektronik", "Bijih timah", "Rempah ratus", "Kain sutera"], "jawapan": "Rempah ratus"},
        {"soalan": "Apakah kepentingan sungai kepada kerajaan Alam Melayu?", "pilihan": ["Tempat membuang sampah", "Tempat memelihara binatang", "Sebagai sempadan negara", "Sebagai laluan perdagangan dan komunikasi"], "jawapan": "Sebagai laluan perdagangan dan komunikasi"},
        {"soalan": "Apakah bentuk pemerintahan kerajaan Alam Melayu?", "pilihan": ["Demokrasi", "Sosialis", "Beraja", "Komunis"], "jawapan": "Beraja"},
        {"soalan": "Raja dianggap suci dalam kerajaan Alam Melayu kerana...", "pilihan": ["Memiliki kekayaan", "Mewarisi darah pahlawan", "Dikaitkan dengan kuasa dewa", "Pernah menewaskan penjajah"], "jawapan": "Dikaitkan dengan kuasa dewa"},
        {"soalan": "Siapakah pemerintah terkenal kerajaan Srivijaya?", "pilihan": ["Parameswara", "Dapunta Hyang", "Che Bong Nga", "Jayavarman VII"], "jawapan": "Dapunta Hyang"},
        {"soalan": "Apakah warisan kebudayaan kerajaan Alam Melayu?", "pilihan": ["Patung Buddha", "Tulisan jawi", "Reka bentuk moden", "Teknologi komputer"], "jawapan": "Patung Buddha"},
        {"soalan": "Apakah kesan kedatangan agama Hindu dan Buddha ke Alam Melayu?", "pilihan": ["Menyebabkan penjajahan", "Mempengaruhi sistem pendidikan moden", "Membentuk struktur sosial dan budaya", "Menggantikan bahasa Melayu"], "jawapan": "Membentuk struktur sosial dan budaya"},
        {"soalan": "Tulisan kuno yang digunakan oleh kerajaan Alam Melayu ialah...", "pilihan": ["Rumi", "Kawi", "Korean", "Sanskrit"], "jawapan": "Kawi"},
        {"soalan": "Kerajaan Alam Melayu banyak didirikan berhampiran...", "pilihan": ["Kawasan pergunungan", "Hutan tebal", "Kawasan pantai dan sungai", "Kawasan tandus"], "jawapan": "Kawasan pantai dan sungai"},
        {"soalan": "Kegiatan utama ekonomi kerajaan Alam Melayu ialah...", "pilihan": ["Perlombongan emas", "Perdagangan", "Pembuatan senjata", "Industri berat"], "jawapan": "Perdagangan"},
        {"soalan": "Agama Islam mula tersebar luas di Alam Melayu pada zaman...", "pilihan": ["Langkasuka", "Majapahit", "Melaka", "Funan"], "jawapan": "Melaka"},
        {"soalan": "Kerajaan Champa kini terletak di negara moden...", "pilihan": ["Malaysia", "Thailand", "Vietnam", "Indonesia"], "jawapan": "Vietnam"},
        {"soalan": "Apakah faktor kemerosotan kerajaan Alam Melayu?", "pilihan": ["Bencana alam", "Penjajahan kuasa Barat", "Kehilangan raja", "Perubahan iklim"], "jawapan": "Penjajahan kuasa Barat"},
        {"soalan": "Bagaimanakah sistem pentadbiran dijalankan dalam kerajaan Alam Melayu?", "pilihan": ["Pemerintahan demokratik", "Pemerintahan berasaskan undang-undang Islam", "Pemerintahan beraja dengan pembesar", "Sistem republik"], "jawapan": "Pemerintahan beraja dengan pembesar"},
        {"soalan": "Kerajaan Srivijaya berkembang maju hasil daripada...", "pilihan": ["Perang dengan China", "Kekuatan tentera laut", "Kekayaan hasil hutan", "Sokongan dari India"], "jawapan": "Kekuatan tentera laut"},
        {"soalan": "Kerajaan Majapahit berpusat di...", "pilihan": ["Sumatera", "Borneo", "Jawa Timur", "Bali"], "jawapan": "Jawa Timur"},
        {"soalan": "Apakah keistimewaan kerajaan Kedah Tua?", "pilihan": ["Terkenal dalam seni ukiran kayu", "Pusat perdagangan awal", "Kawasan perlombongan bijih timah", "Benteng pertahanan yang kukuh"], "jawapan": "Pusat perdagangan awal"},
        {"soalan": "Siapakah tokoh penting kerajaan Majapahit?", "pilihan": ["Hang Tuah", "Gajah Mada", "Jayavarman II", "Parameswara"], "jawapan": "Gajah Mada"},
        {"soalan": "Candi Borobudur dibina semasa pemerintahan...", "pilihan": ["Srivijaya", "Majapahit", "Sailendra", "Champa"], "jawapan": "Sailendra"},
        {"soalan": "Salah satu keunikan masyarakat kerajaan Alam Melayu ialah...", "pilihan": ["Sistem kasta India", "Budaya merantau", "Sistem komunis", "Ekonomi kapitalis"], "jawapan": "Budaya merantau"},
        {"soalan": "Apakah sumbangan kerajaan Alam Melayu kepada sejarah Asia Tenggara?", "pilihan": ["Menjadi empayar kuasa Barat", "Memusnahkan budaya tempatan", "Menjadi pusat tamadun awal", "Menghapuskan pengaruh India"], "jawapan": "Menjadi pusat tamadun awal"},
        {"soalan": "Perdagangan antara kerajaan Alam Melayu dan China dikenali sebagai...", "pilihan": ["Perdagangan bebas", "Hubungan bilateral", "Perdagangan maritim", "Hubungan diplomatik"], "jawapan": "Perdagangan maritim"},
        {"soalan": "Apakah bukti kewujudan kerajaan awal Alam Melayu?", "pilihan": ["Bangunan moden", "Catatan sejarah Barat", "Artifak dan prasasti", "Novel sejarah"], "jawapan": "Artifak dan prasasti"},
        {"soalan": "Apakah fungsi golongan pembesar dalam kerajaan Alam Melayu?", "pilihan": ["Menjadi tentera upahan", "Menjaga ekonomi sahaja", "Membantu raja mentadbir negeri", "Menjajah kawasan lain"], "jawapan": "Membantu raja mentadbir negeri"},
        {"soalan": "Siapakah yang mengasaskan kerajaan Melaka?", "pilihan": ["Parameswara", "Gajah Mada", "Jayavarman", "Fan Shih-man"], "jawapan": "Parameswara"},
        {"soalan": "Mengapakah kerajaan Alam Melayu mudah berkembang?", "pilihan": ["Mempunyai tentera kuat", "Pengaruh agama yang kukuh", "Lokasi strategik dan sumber alam", "Sokongan daripada Barat"], "jawapan": "Lokasi strategik dan sumber alam"},
        {"soalan": "Kerajaan Angkor terkenal dengan pembinaan...", "pilihan": ["Masjid besar", "Candi Borobudur", "Angkor Wat", "Istana besar"], "jawapan": "Angkor Wat"},
        {"soalan": "Kerajaan Champa pernah berperang dengan kerajaan...", "pilihan": ["Langkasuka", "Majapahit", "Vietnam", "Funan"], "jawapan": "Vietnam"},
        {"soalan": "Apakah kesan pengaruh India terhadap Alam Melayu?", "pilihan": ["Kehilangan identiti budaya", "Kemajuan dalam pertanian", "Pengenalan sistem kasta dan agama Hindu-Buddha", "Pembentukan empayar Barat"], "jawapan": "Pengenalan sistem kasta dan agama Hindu-Buddha"}
    ],
  'Bab 2': [
        {"soalan": "Apakah bentuk sistem pemerintahan dalam kerajaan Alam Melayu?", "pilihan": ["Republik", "Beraja", "Demokrasi", "Komunis"], "jawapan": "Beraja"},
        {"soalan": "Siapakah ketua pemerintah dalam sistem pemerintahan beraja?", "pilihan": ["Pembesar", "Bendahara", "Raja", "Penasihat"], "jawapan": "Raja"},
        {"soalan": "Raja dianggap suci kerana dipercayai mempunyai...", "pilihan": ["Keturunan India", "Kebolehan ilmu hitam", "Hubungan dengan dewa", "Asal usul dari pedagang"], "jawapan": "Hubungan dengan dewa"},
        {"soalan": "Apakah tanggungjawab utama seorang raja?", "pilihan": ["Menjadi ketua paderi", "Melantik penjajah", "Mentadbir dan melindungi rakyat", "Menjalankan perdagangan antarabangsa"], "jawapan": "Mentadbir dan melindungi rakyat"},
        {"soalan": "Golongan yang membantu raja dalam pentadbiran dikenali sebagai...", "pilihan": ["Pendeta", "Pembesar", "Pahlawan", "Rakyat"], "jawapan": "Pembesar"},
        {"soalan": "Antara berikut, yang manakah merupakan gelaran pembesar utama?", "pilihan": ["Panglima Hitam", "Tun Mahathir", "Bendahara", "Sultan"], "jawapan": "Bendahara"},
        {"soalan": "Apakah maksud sistem pentadbiran secara hierarki?", "pilihan": ["Semua orang sama rata", "Kedudukan berdasarkan keturunan", "Peraturan datang dari rakyat", "Setiap orang bebas mentadbir"], "jawapan": "Kedudukan berdasarkan keturunan"},
        {"soalan": "Pembesar bertanggungjawab dalam perkara berikut, kecuali...", "pilihan": ["Memungut cukai", "Menjaga keamanan", "Mengisytiharkan perang tanpa kebenaran raja", "Menasihati raja"], "jawapan": "Mengisytiharkan perang tanpa kebenaran raja"},
        {"soalan": "Siapakah rakyat dalam sistem pemerintahan kerajaan Alam Melayu?", "pilihan": ["Orang asing", "Kaum bangsawan sahaja", "Golongan hamba sahaja", "Penduduk yang tinggal di dalam wilayah raja"], "jawapan": "Penduduk yang tinggal di dalam wilayah raja"},
        {"soalan": "Rakyat perlu menunjukkan taat setia kepada...", "pilihan": ["Pembesar", "Sultan negara jiran", "Raja", "Penjajah"], "jawapan": "Raja"},
        {"soalan": "Apakah kegiatan ekonomi utama kerajaan Alam Melayu?", "pilihan": ["Pelancongan", "Perdagangan", "Pembuatan senjata", "Pertanian moden"], "jawapan": "Perdagangan"},
        {"soalan": "Apakah hasil utama dalam kegiatan perdagangan?", "pilihan": ["Teknologi moden", "Rempah ratus", "Minyak mentah", "Elektronik"], "jawapan": "Rempah ratus"},
        {"soalan": "Apakah faktor yang menyumbang kepada kemajuan perdagangan?", "pilihan": ["Lokasi strategik", "Teknologi kapal layar", "Perjanjian Barat", "Dasar cukai tinggi"], "jawapan": "Lokasi strategik"},
        {"soalan": "Sungai dan pelabuhan digunakan sebagai...", "pilihan": ["Tempat pertanian", "Pusat pentadbiran", "Laluan perdagangan dan perhubungan", "Tempat penyimpanan senjata"], "jawapan": "Laluan perdagangan dan perhubungan"},
        {"soalan": "Apakah yang dimaksudkan dengan sistem serahan?", "pilihan": ["Pemberian kuasa kepada raja", "Bayaran cukai dalam bentuk barang", "Penyerahan tanah kepada rakyat", "Penghantaran tentera ke luar negara"], "jawapan": "Bayaran cukai dalam bentuk barang"},
        {"soalan": "Contoh hasil serahan ialah...", "pilihan": ["Senjata dan peluru", "Kapal layar", "Hasil pertanian seperti padi", "Surat rasmi"], "jawapan": "Hasil pertanian seperti padi"},
        {"soalan": "Kegiatan ekonomi yang dijalankan oleh masyarakat di kawasan pedalaman ialah...", "pilihan": ["Perdagangan antarabangsa", "Pertanian sara diri", "Pembinaan kota", "Perkapalan moden"], "jawapan": "Pertanian sara diri"},
        {"soalan": "Kerajaan yang terkenal dengan kegiatan perdagangan ialah...", "pilihan": ["Angkor", "Majapahit", "Funan", "Srivijaya"], "jawapan": "Srivijaya"},
        {"soalan": "Apakah maksud ekonomi sara diri?", "pilihan": ["Pengeluaran untuk eksport", "Pengeluaran bagi kegunaan sendiri", "Ekonomi tanpa kerajaan", "Ekonomi berdasarkan perdagangan luar"], "jawapan": "Pengeluaran bagi kegunaan sendiri"},
        {"soalan": "Antara berikut, manakah bukan kegiatan ekonomi kerajaan Alam Melayu?", "pilihan": ["Pertanian", "Perlombongan", "Perbankan", "Perdagangan"], "jawapan": "Perbankan"},
        {"soalan": "Kegiatan perlombongan dijalankan untuk mendapatkan...", "pilihan": ["Minyak mentah", "Bijih timah dan emas", "Batu marmar", "Garam"], "jawapan": "Bijih timah dan emas"},
        {"soalan": "Apakah tujuan pembesar memungut cukai?", "pilihan": ["Meningkatkan kekayaan peribadi", "Menambah bilangan tentera", "Membiayai pentadbiran dan keselamatan", "Membayar gaji penjajah"], "jawapan": "Membiayai pentadbiran dan keselamatan"},
        {"soalan": "Hubungan antara kerajaan dan rakyat berdasarkan...", "pilihan": ["Undang-undang Barat", "Ketaatan dan perlindungan", "Pemilihan secara pilihan raya", "Perjanjian bertulis"], "jawapan": "Ketaatan dan perlindungan"},
        {"soalan": "Mengapakah kerajaan Alam Melayu berjaya dalam kegiatan ekonomi?", "pilihan": ["Dasar tertutup", "Sistem beraja mutlak", "Penglibatan aktif dalam perdagangan", "Penjajahan kuasa asing"], "jawapan": "Penglibatan aktif dalam perdagangan"},
        {"soalan": "Golongan rakyat perlu menyerahkan hasil pertanian kepada...", "pilihan": ["Orang asing", "Pembesar", "Peniaga dari luar", "Pendeta"], "jawapan": "Pembesar"},
        {"soalan": "Apakah hasil hutan yang menjadi komoditi penting?", "pilihan": ["Kayu balak", "Gula", "Kelapa sawit", "Coklat"], "jawapan": "Kayu balak"},
        {"soalan": "Mengapakah kawasan berhampiran sungai menjadi tumpuan ekonomi?", "pilihan": ["Sumber air minuman", "Mudah mendapat makanan", "Laluan pengangkutan dan perdagangan", "Tempat berkelah"], "jawapan": "Laluan pengangkutan dan perdagangan"},
        {"soalan": "Siapakah yang bertanggungjawab mengutip hasil cukai?", "pilihan": ["Pendeta", "Pembesar daerah", "Rakyat", "Raja"], "jawapan": "Pembesar daerah"},
        {"soalan": "Apakah ciri ekonomi kerajaan Alam Melayu?", "pilihan": ["Berorientasikan eksport", "Bergantung kepada bantuan asing", "Bersifat sara diri dan perdagangan", "Bersifat industri berat"], "jawapan": "Bersifat sara diri dan perdagangan"},
        {"soalan": "Kegiatan ekonomi kerajaan Alam Melayu banyak dipengaruhi oleh...", "pilihan": ["Kedatangan British", "Lokasi geografi dan sumber semula jadi", "Sistem kapitalis", "Perdagangan elektronik"], "jawapan": "Lokasi geografi dan sumber semula jadi"},
        {"soalan": "Kegiatan pertanian dijalankan oleh...", "pilihan": ["Pembesar", "Rakyat biasa", "Peniaga asing", "Raja"], "jawapan": "Rakyat biasa"},
        {"soalan": "Apakah hasil pertanian utama masyarakat kerajaan Alam Melayu?", "pilihan": ["Kelapa sawit", "Padi", "Jagung", "Tebu"], "jawapan": "Padi"},
        {"soalan": "Sistem pembesar empat lipatan merujuk kepada...", "pilihan": ["Empat jenis pembesar berbeza", "Empat peringkat pentadbiran", "Empat kawasan pertanian", "Empat jenis cukai"], "jawapan": "Empat jenis pembesar berbeza"},
        {"soalan": "Apakah peranan golongan pembesar dalam hal ekonomi?", "pilihan": ["Melabur dalam pelaburan asing", "Menjadi pedagang antarabangsa", "Memungut cukai dan mengurus hasil", "Membangunkan industri teknologi"], "jawapan": "Memungut cukai dan mengurus hasil"},
        {"soalan": "Apakah tujuan sistem pembesar diwujudkan?", "pilihan": ["Mengurangkan kuasa raja", "Menjaga keselamatan sahaja", "Membantu raja mentadbir dan mengurus ekonomi", "Melaksanakan undang-undang Barat"], "jawapan": "Membantu raja mentadbir dan mengurus ekonomi"},
        {"soalan": "Pusat perdagangan utama kerajaan Alam Melayu ialah...", "pilihan": ["Bukit Tinggi", "Lembah Bujang", "Gunung Tahan", "Temasek"], "jawapan": "Temasek"},
        {"soalan": "Apakah hasil laut yang diperdagangkan oleh masyarakat kerajaan Alam Melayu?", "pilihan": ["Minyak ikan", "Ikan bilis dan garam", "Teripang dan mutiara", "Sotong kurita"], "jawapan": "Teripang dan mutiara"},
        {"soalan": "Apakah kelebihan sistem ekonomi bercorak tradisional?", "pilihan": ["Penggunaan teknologi tinggi", "Hubungan erat antara pemerintah dan rakyat", "Cepat berkembang seperti negara maju", "Kurang peranan raja"], "jawapan": "Hubungan erat antara pemerintah dan rakyat"}
    ],
  'Bab 3': [
        {"soalan": "Apakah maksud sosio budaya?", "pilihan": ["Asal usul masyarakat", "Gabungan aspek sosial dan budaya sesebuah masyarakat", "Pengaruh luar terhadap kerajaan", "Sistem pemerintahan beraja"], "jawapan": "Gabungan aspek sosial dan budaya sesebuah masyarakat"},
        {"soalan": "Apakah bahasa utama yang digunakan dalam kerajaan Alam Melayu?", "pilihan": ["Bahasa Inggeris", "Bahasa Melayu", "Bahasa Sanskrit", "Bahasa Arab"], "jawapan": "Bahasa Melayu"},
        {"soalan": "Tulisan yang digunakan oleh masyarakat kerajaan Alam Melayu ialah...", "pilihan": ["Jawi dan Rumi", "Sanskrit dan Kawi", "Tamil dan Cina", "Latin dan Greek"], "jawapan": "Sanskrit dan Kawi"},
        {"soalan": "Apakah tujuan utama penggunaan tulisan dalam kerajaan Alam Melayu?", "pilihan": ["Menulis cerita rakyat", "Mencatat rekod perdagangan", "Tujuan keagamaan dan peringatan sejarah", "Melakar lukisan"], "jawapan": "Tujuan keagamaan dan peringatan sejarah"},
        {"soalan": "Apakah bentuk kesenian utama dalam masyarakat Alam Melayu?", "pilihan": ["Drama moden", "Ukiran kayu dan batu", "Seni bina konkrit", "Lukisan abstrak"], "jawapan": "Ukiran kayu dan batu"},
        {"soalan": "Apakah nama candi terkenal yang terdapat di Lembah Bujang?", "pilihan": ["Candi Borobudur", "Candi Angkor Wat", "Candi Batu Pahat", "Candi Bukit Batu Pahat"], "jawapan": "Candi Bukit Batu Pahat"},
        {"soalan": "Kesenian ukiran masyarakat Alam Melayu sering dikaitkan dengan...", "pilihan": ["Perdagangan", "Agama dan kepercayaan", "Perang", "Pendidikan"], "jawapan": "Agama dan kepercayaan"},
        {"soalan": "Masyarakat kerajaan Alam Melayu mengamalkan kepercayaan seperti...", "pilihan": ["Animisme, Hindu, Buddha", "Islam dan Kristian", "Atheisme dan Sains", "Zoroastrianisme"], "jawapan": "Animisme, Hindu, Buddha"},
        {"soalan": "Apakah tujuan pembinaan candi dalam masyarakat Alam Melayu?", "pilihan": ["Sebagai gudang senjata", "Tempat menyimpan makanan", "Tempat keagamaan dan penyembahan", "Pusat perdagangan"], "jawapan": "Tempat keagamaan dan penyembahan"},
        {"soalan": "Salah satu contoh budaya lisan dalam masyarakat Alam Melayu ialah...", "pilihan": ["Candi", "Syair", "Prasasti", "Tulisan batu"], "jawapan": "Syair"},
        {"soalan": "Apakah peranan bahasa dalam masyarakat kerajaan Alam Melayu?", "pilihan": ["Sebagai alat peperangan", "Sebagai simbol kekayaan", "Sebagai alat komunikasi dan penyatuan", "Sebagai pengganti sistem tulisan"], "jawapan": "Sebagai alat komunikasi dan penyatuan"},
        {"soalan": "Contoh prasasti yang terkenal di Alam Melayu ialah...", "pilihan": ["Prasasti Palembang", "Prasasti Batu Bersurat", "Prasasti Champa", "Prasasti Angkor"], "jawapan": "Prasasti Batu Bersurat"},
        {"soalan": "Apakah keistimewaan Prasasti Batu Bersurat?", "pilihan": ["Ditulis dalam bahasa Latin", "Mencatatkan perjanjian perdagangan", "Mengandungi unsur keagamaan dan pentadbiran", "Menceritakan kisah dongeng"], "jawapan": "Mengandungi unsur keagamaan dan pentadbiran"},
        {"soalan": "Agama Hindu dan Buddha disebarkan ke Alam Melayu melalui...", "pilihan": ["Serangan tentera India", "Perkahwinan diraja", "Perdagangan dan hubungan luar", "Penjajahan secara langsung"], "jawapan": "Perdagangan dan hubungan luar"},
        {"soalan": "Apakah hasil kesusasteraan utama pada zaman kerajaan Alam Melayu?", "pilihan": ["Hikayat dan pantun", "Puisi moden", "Novel realistik", "Karangan ilmiah"], "jawapan": "Hikayat dan pantun"},
        {"soalan": "Apakah maksud hikayat dalam sastera Melayu?", "pilihan": ["Karangan berita", "Karya sejarah rasmi", "Karya prosa yang mengandungi unsur pengembaraan dan kepahlawanan", "Karya sains dan matematik"], "jawapan": "Karya prosa yang mengandungi unsur pengembaraan dan kepahlawanan"},
        {"soalan": "Pantun digunakan dalam masyarakat Alam Melayu untuk...", "pilihan": ["Memberi arahan rasmi", "Tujuan hiburan dan pengajaran", "Menulis undang-undang", "Tujuan peperangan"], "jawapan": "Tujuan hiburan dan pengajaran"},
        {"soalan": "Apakah kesan penyebaran agama Hindu dan Buddha terhadap seni bina?", "pilihan": ["Membina masjid besar", "Melahirkan seni bina bercorak keagamaan seperti candi", "Menghasilkan senjata baharu", "Memusnahkan binaan tradisional"], "jawapan": "Melahirkan seni bina bercorak keagamaan seperti candi"},
        {"soalan": "Seni bina kerajaan Alam Melayu banyak dipengaruhi oleh...", "pilihan": ["Jepun", "Eropah", "India", "China"], "jawapan": "India"},
        {"soalan": "Candi dibina menggunakan bahan seperti...", "pilihan": ["Simen moden", "Kayu jati", "Batu laterit dan bata", "Tanah liat"], "jawapan": "Batu laterit dan bata"},
        {"soalan": "Apakah jenis pendidikan dalam masyarakat kerajaan Alam Melayu?", "pilihan": ["Formal di sekolah sahaja", "Tidak wujud pendidikan", "Tidak teratur", "Tidak formal melalui pengajaran lisan dan agama"], "jawapan": "Tidak formal melalui pengajaran lisan dan agama"},
        {"soalan": "Siapakah yang berperanan menyampaikan ilmu dalam masyarakat kerajaan Alam Melayu?", "pilihan": ["Peniaga", "Pendeta dan golongan agama", "Pembesar", "Hamba"], "jawapan": "Pendeta dan golongan agama"},
        {"soalan": "Agama memainkan peranan penting dalam pembentukan...", "pilihan": ["Sistem pertanian", "Reka bentuk kapal", "Nilai dan etika masyarakat", "Perdagangan antarabangsa"], "jawapan": "Nilai dan etika masyarakat"},
        {"soalan": "Karya kesusasteraan digunakan untuk...", "pilihan": ["Menjual barang", "Mendidik masyarakat", "Menyerang musuh", "Menyimpan hasil bumi"], "jawapan": "Mendidik masyarakat"},
        {"soalan": "Seni muzik tradisional sering dimainkan dalam...", "pilihan": ["Majlis rasmi kerajaan", "Perang", "Majlis keagamaan dan keramaian", "Pasar malam"], "jawapan": "Majlis keagamaan dan keramaian"},
        {"soalan": "Contoh alat muzik tradisional Alam Melayu ialah...", "pilihan": ["Seruling, gamelan, rebab", "Piano, gitar, biola", "Drum elektrik", "Sitar dan tabla"], "jawapan": "Seruling, gamelan, rebab"},
        {"soalan": "Apakah tujuan tarian tradisional dalam masyarakat Alam Melayu?", "pilihan": ["Tunjuk perasaan", "Upacara penyembahan dan hiburan", "Latihan ketenteraan", "Pendidikan sains"], "jawapan": "Upacara penyembahan dan hiburan"},
        {"soalan": "Apakah bentuk kepercayaan awal masyarakat sebelum agama Hindu-Buddha?", "pilihan": ["Zoroaster", "Animisme dan dinamisme", "Kristian", "Islam"], "jawapan": "Animisme dan dinamisme"},
        {"soalan": "Apakah peranan istana dalam kebudayaan masyarakat?", "pilihan": ["Pusat peperangan", "Tempat persembunyian", "Pusat penyebaran budaya dan keagamaan", "Gudang senjata"], "jawapan": "Pusat penyebaran budaya dan keagamaan"},
        {"soalan": "Salah satu tokoh yang dikaitkan dengan kesusasteraan Melayu klasik ialah...", "pilihan": ["Hang Tuah", "Parameswara", "Gajah Mada", "Jayavarman"], "jawapan": "Hang Tuah"},
        {"soalan": "Seni persembahan seperti wayang kulit berasal dari pengaruh...", "pilihan": ["India", "Arab", "Cina", "Jepun"], "jawapan": "India"},
        {"soalan": "Apakah keunikan budaya masyarakat Alam Melayu?", "pilihan": ["Kepelbagaian dan nilai murni", "Teknologi tinggi", "Bahasa asing", "Sistem kasta"], "jawapan": "Kepelbagaian dan nilai murni"},
        {"soalan": "Manakah antara berikut ialah hasil kesusasteraan berbentuk prosa?", "pilihan": ["Pantun", "Syair", "Hikayat", "Gurindam"], "jawapan": "Hikayat"},
        {"soalan": "Apakah bentuk warisan budaya bukan kebendaan?", "pilihan": ["Candi", "Prasasti", "Adat dan kepercayaan", "Ukiran batu"], "jawapan": "Adat dan kepercayaan"},
        {"soalan": "Apakah nilai yang diamalkan dalam budaya masyarakat Alam Melayu?", "pilihan": ["Kebebasan mutlak", "Kesetiaan, hormat, kerjasama", "Kejayaan peribadi", "Persaingan bebas"], "jawapan": "Kesetiaan, hormat, kerjasama"},
        {"soalan": "Apakah kesan budaya India terhadap Alam Melayu?", "pilihan": ["Menghapuskan budaya tempatan", "Menggantikan bahasa Melayu", "Memperkaya budaya tempatan", "Menyekat perkembangan kesusasteraan"], "jawapan": "Memperkaya budaya tempatan"},
        {"soalan": "Siapakah golongan yang memelihara dan menyampaikan budaya tempatan?", "pilihan": ["Raja dan permaisuri", "Pahlawan", "Golongan tua dan pendeta", "Peniaga luar"], "jawapan": "Golongan tua dan pendeta"},
        {"soalan": "Bahasa Sanskrit digunakan dalam...", "pilihan": ["Tulisan rasmi dan keagamaan", "Perdagangan harian", "Upacara kematian", "Pendidikan moden"], "jawapan": "Tulisan rasmi dan keagamaan"},
        {"soalan": "Candi Borobudur merupakan bukti...", "pilihan": ["Pengaruh Islam", "Kebudayaan tradisional Arab", "Seni bina Buddha", "Ciptaan penjajah"], "jawapan": "Seni bina Buddha"}
    ],
  'Bab 4': [
        {"soalan": "Apakah agama yang dianuti oleh masyarakat kerajaan Alam Melayu sebelum kedatangan agama Hindu dan Buddha?", "pilihan": ["Islam", "Animisme dan dinamisme", "Kristian", "Zoroastrianisme"], "jawapan": "Animisme dan dinamisme"},
        {"soalan": "Agama Hindu dan Buddha mula tersebar ke Alam Melayu melalui...", "pilihan": ["Penjajahan Eropah", "Hubungan perdagangan dan perkahwinan diraja", "Penyebaran melalui misi agama", "Penaklukan ketenteraan"], "jawapan": "Hubungan perdagangan dan perkahwinan diraja"},
        {"soalan": "Apakah agama utama kerajaan Angkor?", "pilihan": ["Buddha Mahayana", "Hindu", "Islam", "Animisme"], "jawapan": "Hindu"},
        {"soalan": "Apakah nama candi terkenal yang dibina sebagai tempat ibadat masyarakat Angkor?", "pilihan": ["Candi Prambanan", "Candi Lembah Bujang", "Candi Borobudur", "Angkor Wat"], "jawapan": "Angkor Wat"},
        {"soalan": "Apakah fungsi utama candi dalam masyarakat kerajaan Alam Melayu?", "pilihan": ["Pusat perdagangan", "Pusat ketenteraan", "Tempat ibadat dan keagamaan", "Kediaman pembesar"], "jawapan": "Tempat ibadat dan keagamaan"},
        {"soalan": "Agama Buddha mula tersebar ke Alam Melayu melalui...", "pilihan": ["Perang salib", "Hubungan diplomatik", "Perdagangan dan pendakwah", "Penjajahan Barat"], "jawapan": "Perdagangan dan pendakwah"},
        {"soalan": "Kerajaan Srivijaya terkenal sebagai pusat...", "pilihan": ["Pentadbiran Islam", "Penyebaran agama Buddha", "Perindustrian", "Sains dan teknologi"], "jawapan": "Penyebaran agama Buddha"},
        {"soalan": "Tulisan suci yang digunakan dalam upacara agama Hindu ialah...", "pilihan": ["Surah", "Tripitaka", "Veda", "Weda"], "jawapan": "Veda"},
        {"soalan": "Apakah kepercayaan animisme?", "pilihan": ["Penyembahan roh dan alam semula jadi", "Kepercayaan kepada Tuhan yang Esa", "Kepercayaan kepada sains", "Tiada kepercayaan"], "jawapan": "Penyembahan roh dan alam semula jadi"},
        {"soalan": "Dinamisme ialah kepercayaan kepada...", "pilihan": ["Roh nenek moyang", "Benda-benda tertentu yang mempunyai kuasa ghaib", "Hidupan laut", "Ilmu sains moden"], "jawapan": "Benda-benda tertentu yang mempunyai kuasa ghaib"},
        {"soalan": "Kepercayaan animisme dan dinamisme masih diamalkan oleh...", "pilihan": ["Masyarakat bandar", "Masyarakat minoriti", "Peniaga asing", "Pemerintah"], "jawapan": "Masyarakat minoriti"},
        {"soalan": "Agama Hindu mengajar konsep kasta seperti Brahmin dan...", "pilihan": ["Ulama", "Sudra", "Wali", "Sangha"], "jawapan": "Sudra"},
        {"soalan": "Apakah ciri khas seni bina candi?", "pilihan": ["Reka bentuk moden", "Reka bentuk pelbagai tingkat dengan tangga dan ukiran", "Tiang besi dan kaca", "Kubur batu besar"], "jawapan": "Reka bentuk pelbagai tingkat dengan tangga dan ukiran"},
        {"soalan": "Apakah pengaruh agama terhadap sistem sosial masyarakat?", "pilihan": ["Menolak adat", "Menghapuskan kepercayaan", "Mewujudkan hierarki dan nilai moral", "Membentuk ekonomi moden"], "jawapan": "Mewujudkan hierarki dan nilai moral"},
        {"soalan": "Apakah konsep 'dharma' dalam agama Hindu?", "pilihan": ["Keadilan sosial", "Undang-undang raja", "Tanggungjawab moral dan etika", "Pembalasan karma"], "jawapan": "Tanggungjawab moral dan etika"},
        {"soalan": "Upacara keagamaan masyarakat Hindu dan Buddha dijalankan di...", "pilihan": ["Masjid", "Candi", "Kuil moden", "Istana"], "jawapan": "Candi"},
        {"soalan": "Salah satu bentuk warisan budaya yang berkait dengan keagamaan ialah...", "pilihan": ["Pantun cinta", "Candi dan prasasti", "Pasar malam", "Tarian moden"], "jawapan": "Candi dan prasasti"},
        {"soalan": "Warisan budaya kebendaan termasuk...", "pilihan": ["Pantun dan syair", "Candi dan arca", "Adat dan nilai", "Bahasa pertuturan"], "jawapan": "Candi dan arca"},
        {"soalan": "Warisan budaya bukan kebendaan ialah...", "pilihan": ["Tulisan batu", "Candi", "Bahasa, adat dan kepercayaan", "Patung dewa"], "jawapan": "Bahasa, adat dan kepercayaan"},
        {"soalan": "Bagaimanakah agama dan kepercayaan disebarkan dalam masyarakat?", "pilihan": ["Melalui sistem pendidikan moden", "Melalui penjajahan Barat", "Melalui perdagangan, perkahwinan dan pendakwah", "Melalui siaran radio"], "jawapan": "Melalui perdagangan, perkahwinan dan pendakwah"},
        {"soalan": "Apakah bentuk seni halus yang berkaitan dengan kepercayaan?", "pilihan": ["Ukiran dan arca keagamaan", "Karya realisme", "Lukisan abstrak", "Fotografi moden"], "jawapan": "Ukiran dan arca keagamaan"},
        {"soalan": "Arca Buddha biasanya diperbuat daripada...", "pilihan": ["Tanah liat", "Kaca", "Emas dan gangsa", "Kain sutera"], "jawapan": "Emas dan gangsa"},
        {"soalan": "Salah satu ciri unik warisan masyarakat Alam Melayu ialah...", "pilihan": ["Reka bentuk moden", "Kepelbagaian budaya dan agama", "Satu bahasa sahaja", "Tiada sistem tulisan"], "jawapan": "Kepelbagaian budaya dan agama"},
        {"soalan": "Apakah fungsi utama prasasti?", "pilihan": ["Papan iklan", "Catatan sejarah dan keagamaan", "Kod undang-undang moden", "Senarai pembesar"], "jawapan": "Catatan sejarah dan keagamaan"},
        {"soalan": "Apakah bahan yang digunakan untuk membuat prasasti?", "pilihan": ["Kertas", "Besi", "Batu dan logam", "Kaca"], "jawapan": "Batu dan logam"},
        {"soalan": "Mengapakah warisan budaya penting untuk dikekalkan?", "pilihan": ["Menarik pelancong sahaja", "Untuk tujuan keuntungan", "Sebagai identiti dan jati diri bangsa", "Menggambarkan kemajuan teknologi"], "jawapan": "Sebagai identiti dan jati diri bangsa"},
        {"soalan": "Warisan budaya dapat memperkukuh...", "pilihan": ["Ekonomi semata-mata", "Sistem peperangan", "Identiti kebangsaan", "Hubungan dengan penjajah"], "jawapan": "Identiti kebangsaan"},
        {"soalan": "Apakah kesan pengaruh Hindu-Buddha terhadap Alam Melayu?", "pilihan": ["Menyingkirkan budaya asal", "Menghapuskan bahasa Melayu", "Memperkaya warisan budaya tempatan", "Menyebabkan penjajahan"], "jawapan": "Memperkaya warisan budaya tempatan"},
        {"soalan": "Apakah kepentingan arca dalam kepercayaan Buddha?", "pilihan": ["Sebagai alat peperangan", "Sebagai alat perubatan", "Simbol penyembahan dan ajaran", "Perhiasan istana"], "jawapan": "Simbol penyembahan dan ajaran"},
        {"soalan": "Warisan budaya boleh dikekalkan melalui...", "pilihan": ["Melupuskan adat lama", "Mengimport budaya asing", "Pendidikan dan penghayatan masyarakat", "Pembangunan pesat"], "jawapan": "Pendidikan dan penghayatan masyarakat"},
        {"soalan": "Apakah nilai murni yang diajar dalam agama Hindu dan Buddha?", "pilihan": ["Kemewahan dan kekayaan", "Pengejaran kuasa", "Kesederhanaan dan keharmonian", "Kekuasaan mutlak"], "jawapan": "Kesederhanaan dan keharmonian"},
        {"soalan": "Candi Prambanan terletak di...", "pilihan": ["Thailand", "Vietnam", "Indonesia", "Kemboja"], "jawapan": "Indonesia"},
        {"soalan": "Apakah kepentingan Angkor Wat kepada sejarah?", "pilihan": ["Pusat politik moden", "Contoh seni bina Islam", "Bukti kebesaran agama dan seni bina masyarakat", "Pusat latihan tentera"], "jawapan": "Bukti kebesaran agama dan seni bina masyarakat"},
        {"soalan": "Kepercayaan dalam masyarakat Alam Melayu membentuk...", "pilihan": ["Sistem sosial dan budaya", "Sistem pertahanan", "Rangkaian perniagaan luar", "Sistem pertanian moden"], "jawapan": "Sistem sosial dan budaya"},
        {"soalan": "Upacara keagamaan tradisional dilakukan untuk tujuan...", "pilihan": ["Pesta rakyat", "Perubatan dan penyembahan", "Perkahwinan diraja", "Peperangan"], "jawapan": "Perubatan dan penyembahan"},
        {"soalan": "Seni ukiran keagamaan biasanya memaparkan imej dewa atau...", "pilihan": ["Raja", "Bunga", "Pahlawan", "Tokoh sufi"], "jawapan": "Raja"},
        {"soalan": "Warisan budaya masyarakat Alam Melayu mencerminkan...", "pilihan": ["Kemiskinan dan peperangan", "Pengaruh Eropah", "Kepelbagaian agama dan kepercayaan", "Perdagangan luar"], "jawapan": "Kepelbagaian agama dan kepercayaan"},
        {"soalan": "Pentingnya memahami warisan kepercayaan ialah untuk...", "pilihan": ["Melawan budaya lain", "Menghapuskan sejarah lama", "Mempupuk perpaduan dan toleransi", "Meniru budaya luar"], "jawapan": "Mempupuk perpaduan dan toleransi"}
    ],
  'Bab 5': [
        {"soalan": "Kesultanan Melayu Melaka diasaskan oleh...", "pilihan": ["Parameswara", "Sultan Mahmud", "Tun Perak", "Hang Tuah"], "jawapan": "Parameswara"},
        {"soalan": "Apakah gelaran yang digunakan oleh raja Melaka selepas memeluk Islam?", "pilihan": ["Sultan", "Maharaja", "Yang Dipertuan", "Datuk"], "jawapan": "Sultan"},
        {"soalan": "Siapakah pembesar yang memainkan peranan penting dalam pentadbiran Melaka?", "pilihan": ["Bendahara", "Syahbandar", "Penghulu Bendahari", "Temenggung"], "jawapan": "Bendahara"},
        {"soalan": "Apakah jawatan yang bertanggungjawab menjaga keselamatan dalam negeri?", "pilihan": ["Temenggung", "Laksamana", "Bendahara", "Syahbandar"], "jawapan": "Temenggung"},
        {"soalan": "Sistem pentadbiran Melaka terbahagi kepada dua iaitu...", "pilihan": ["Pusat dan jajahan", "Raja dan rakyat", "Istana dan balai", "Dalam dan luar negeri"], "jawapan": "Pusat dan jajahan"},
        {"soalan": "Apakah fungsi utama Syahbandar?", "pilihan": ["Mengurus perdagangan", "Menjaga keselamatan", "Menasihati raja", "Memungut cukai"], "jawapan": "Mengurus perdagangan"},
        {"soalan": "Apakah gelaran pembesar yang bertugas sebagai ketua angkatan laut?", "pilihan": ["Laksamana", "Temenggung", "Bendahara", "Syahbandar"], "jawapan": "Laksamana"},
        {"soalan": "Hang Tuah dikenali sebagai...", "pilihan": ["Pahlawan terbilang Melaka", "Pembesar istana", "Bendahara bijak", "Raja Melaka"], "jawapan": "Pahlawan terbilang Melaka"},
        {"soalan": "Kesultanan Melayu Melaka mencapai kegemilangan pada zaman pemerintahan...", "pilihan": ["Sultan Mansur Shah", "Parameswara", "Sultan Mahmud Shah", "Sultan Alauddin"], "jawapan": "Sultan Mansur Shah"},
        {"soalan": "Apakah yang menyebabkan Melaka menjadi pusat perdagangan terkenal?", "pilihan": ["Lokasi strategik", "Rakyat ramai", "Sultan adil", "Pertahanan kuat"], "jawapan": "Lokasi strategik"},
        {"soalan": "Undang-undang utama yang diamalkan di Melaka ialah...", "pilihan": ["Hukum Kanun Melaka", "Hukum Laut", "Undang-Undang Laut", "Hukum Syariah"], "jawapan": "Hukum Kanun Melaka"},
        {"soalan": "Siapakah tokoh undang-undang yang menggubal Hukum Kanun Melaka?", "pilihan": ["Bendahara Tun Perak", "Hang Tuah", "Sultan Mansur Shah", "Tun Mutahir"], "jawapan": "Bendahara Tun Perak"},
        {"soalan": "Apakah faktor utama kemerosotan Kesultanan Melayu Melaka?", "pilihan": ["Serangan Portugis", "Ekonomi lemah", "Perpecahan rakyat", "Sultan uzur"], "jawapan": "Serangan Portugis"},
        {"soalan": "Portugis menyerang Melaka pada tahun...", "pilihan": ["1511", "1500", "1491", "1521"], "jawapan": "1511"},
        {"soalan": "Apakah peranan Bendahara dalam pentadbiran Melaka?", "pilihan": ["Menasihati sultan", "Menjaga perdagangan", "Mengumpul hasil bumi", "Menjadi ketua tentera"], "jawapan": "Menasihati sultan"},
        {"soalan": "Siapakah antara berikut ialah tokoh pembesar Melaka?", "pilihan": ["Tun Perak", "Hang Lekir", "Tun Teja", "Megat Panji Alam"], "jawapan": "Tun Perak"},
        {"soalan": "Bahasa rasmi Kesultanan Melayu Melaka ialah...", "pilihan": ["Bahasa Melayu", "Bahasa Jawa", "Bahasa Arab", "Bahasa Sanskrit"], "jawapan": "Bahasa Melayu"},
        {"soalan": "Melaka mengamalkan sistem pentadbiran...", "pilihan": ["Berhierarki", "Demokrasi", "Autonomi", "Majlis Syura"], "jawapan": "Berhierarki"},
        {"soalan": "Antara berikut, manakah pusat keagamaan penting di Melaka?", "pilihan": ["Masjid Kampung Hulu", "Masjid Sultan", "Masjid Negeri", "Masjid Kapitan Keling"], "jawapan": "Masjid Kampung Hulu"},
        {"soalan": "Sultan Mahmud Shah melarikan diri ke...", "pilihan": ["Bentayan", "Johor", "Perak", "Temasik"], "jawapan": "Bentayan"},
        {"soalan": "Undang-undang Laut Melaka digunakan untuk...", "pilihan": ["Menguruskan perdagangan di laut", "Memungut cukai", "Menentukan hukuman", "Menguruskan tentera laut"], "jawapan": "Menguruskan perdagangan di laut"},
        {"soalan": "Hang Jebat dianggap...", "pilihan": ["Penderhaka", "Wira", "Pendamai", "Pemimpin"], "jawapan": "Penderhaka"},
        {"soalan": "Tun Fatimah terkenal sebagai...", "pilihan": ["Isteri Sultan Mahmud Shah", "Ibu kepada Bendahara", "Ratu Melaka", "Tokoh pendamai"], "jawapan": "Isteri Sultan Mahmud Shah"},
        {"soalan": "Apakah sumber kekayaan utama Melaka?", "pilihan": ["Perdagangan", "Pertanian", "Perikanan", "Perlombongan"], "jawapan": "Perdagangan"},
        {"soalan": "Antara berikut, siapakah bukan pahlawan Melaka?", "pilihan": ["Hang Nadim", "Hang Jebat", "Hang Kasturi", "Hang Lekir"], "jawapan": "Hang Nadim"},
        {"soalan": "Sultan pertama yang memeluk Islam di Melaka ialah...", "pilihan": ["Sultan Muhammad Shah", "Parameswara", "Sultan Mansur Shah", "Sultan Mahmud Shah"], "jawapan": "Sultan Muhammad Shah"},
        {"soalan": "Sistem pembesar empat lipatan terdiri daripada Bendahara, Temenggung, Laksamana dan...", "pilihan": ["Penghulu Bendahari", "Syahbandar", "Pembesar daerah", "Orang Besar 4"], "jawapan": "Penghulu Bendahari"},
        {"soalan": "Apakah bentuk sumbangan Hang Tuah kepada Melaka?", "pilihan": ["Kesetiaan dan keberanian", "Ilmu pertukangan", "Kepimpinan agama", "Menjadi Bendahara"], "jawapan": "Kesetiaan dan keberanian"},
        {"soalan": "Melaka menjadi pusat penyebaran agama Islam melalui...", "pilihan": ["Perdagangan dan perkahwinan diraja", "Penjajahan", "Sekolah rasmi", "Pembesar"], "jawapan": "Perdagangan dan perkahwinan diraja"},
        {"soalan": "Apakah fungsi Temenggung di Melaka?", "pilihan": ["Menjaga keselamatan dan undang-undang", "Mengurus pelabuhan", "Ketua angkatan laut", "Mengutip cukai"], "jawapan": "Menjaga keselamatan dan undang-undang"},
        {"soalan": "Siapakah sultan Melaka terakhir sebelum kejatuhan kepada Portugis?", "pilihan": ["Sultan Mahmud Shah", "Sultan Alauddin Riayat Shah", "Sultan Muhammad Shah", "Sultan Mansur Shah"], "jawapan": "Sultan Mahmud Shah"},
        {"soalan": "Apakah keistimewaan Hukum Kanun Melaka?", "pilihan": ["Menggabungkan adat dan Islam", "Sama dengan undang-undang British", "Diguna oleh semua negeri", "Dicipta oleh Portugis"], "jawapan": "Menggabungkan adat dan Islam"},
        {"soalan": "Apakah peranan Laksamana di Melaka?", "pilihan": ["Menjaga laut dan pertahanan", "Ketua tentera darat", "Menasihati sultan", "Ketua perdagangan"], "jawapan": "Menjaga laut dan pertahanan"},
        {"soalan": "Sistem pengangkutan utama di Melaka ialah...", "pilihan": ["Laut", "Kereta lembu", "Sungai", "Kereta api"], "jawapan": "Laut"},
        {"soalan": "Melaka terkenal dalam perdagangan antarabangsa kerana...", "pilihan": ["Pelabuhannya bebas cukai", "Letaknya di Selat Melaka", "Rakyatnya ramah", "Cuacanya baik"], "jawapan": "Letaknya di Selat Melaka"},
        {"soalan": "Apakah kesan penjajahan Portugis ke atas Melaka?", "pilihan": ["Kehilangan pusat perdagangan", "Kemajuan ekonomi", "Pertahanan bertambah", "Kebebasan agama Islam"], "jawapan": "Kehilangan pusat perdagangan"},
        {"soalan": "Apakah keunikan sistem undang-undang Melaka?", "pilihan": ["Gabungan hukum adat dan Islam", "Sama seperti Eropah", "Tiada hukuman mati", "Hanya lisan"], "jawapan": "Gabungan hukum adat dan Islam"},
        {"soalan": "Apakah kepentingan pelabuhan Melaka pada zaman Kesultanan?", "pilihan": ["Pusat dagangan utama di Asia Tenggara", "Pusat pertanian", "Markas tentera", "Kawasan perikanan"], "jawapan": "Pusat dagangan utama di Asia Tenggara"},
        {"soalan": "Hang Kasturi terkenal sebagai...", "pilihan": ["Sahabat Hang Tuah", "Pembesar istana", "Bendahara", "Pelayar"], "jawapan": "Sahabat Hang Tuah"}
    ],
  'Bab 6': [
        {"soalan": "Apakah nama kerajaan yang diasaskan selepas kejatuhan Melaka pada tahun 1511?", "pilihan": ["Kesultanan Pahang", "Kesultanan Johor Riau", "Kesultanan Perak", "Kesultanan Kedah"], "jawapan": "Kesultanan Johor Riau"},
        {"soalan": "Siapakah pengasas Kesultanan Johor Riau?", "pilihan": ["Sultan Alauddin Riayat Shah II", "Sultan Mahmud Shah", "Raja Kecil", "Bendahara Tun Abdul Majid"], "jawapan": "Sultan Alauddin Riayat Shah II"},
        {"soalan": "Apakah nama pusat pemerintahan awal Kesultanan Johor Riau?", "pilihan": ["Kota Tinggi", "Pekan", "Tanjung Puteri", "Kuala Selangor"], "jawapan": "Kota Tinggi"},
        {"soalan": "Kesultanan Johor Riau diasaskan oleh waris dari...", "pilihan": ["Kesultanan Melaka", "Kesultanan Kedah", "Kesultanan Acheh", "Kesultanan Perlis"], "jawapan": "Kesultanan Melaka"},
        {"soalan": "Apakah strategi Kesultanan Johor Riau untuk mengelakkan ancaman Portugis?", "pilihan": ["Menyerang Melaka secara langsung", "Berpindah-pindah pusat pemerintahan", "Menyerahkan kuasa kepada Belanda", "Menjalinkan hubungan dengan Siam"], "jawapan": "Berpindah-pindah pusat pemerintahan"},
        {"soalan": "Apakah nama pusat pemerintahan yang dibina selepas Kota Tinggi?", "pilihan": ["Batu Sawar", "Pulau Bentan", "Riau", "Lingga"], "jawapan": "Batu Sawar"},
        {"soalan": "Mengapakah Kesultanan Johor Riau sering berpindah pusat pemerintahan?", "pilihan": ["Serangan Belanda", "Tekanan dari Acheh", "Ancaman Portugis", "Bencana alam"], "jawapan": "Ancaman Portugis"},
        {"soalan": "Apakah faktor penting yang membantu pemulihan Kesultanan Johor Riau?", "pilihan": ["Hubungan dengan Siam", "Perdagangan rempah", "Kerjasama dengan Belanda", "Sokongan rakyat"], "jawapan": "Kerjasama dengan Belanda"},
        {"soalan": "Kesultanan Johor Riau mencapai kemuncak kegemilangannya pada zaman pemerintahan...", "pilihan": ["Sultan Abdul Jalil", "Sultan Ahmad", "Sultan Mahmud Shah II", "Sultan Ibrahim"], "jawapan": "Sultan Mahmud Shah II"},
        {"soalan": "Apakah cabaran utama yang dihadapi oleh Kesultanan Johor Riau?", "pilihan": ["Serangan Siam", "Perpecahan dalam istana", "Penjajahan Sepanyol", "Serangan Portugis dan Acheh"], "jawapan": "Serangan Portugis dan Acheh"},
        {"soalan": "Siapakah yang memainkan peranan penting dalam membantu Sultan mentadbir Kesultanan Johor Riau?", "pilihan": ["Syahbandar", "Pembesar Empat Lipatan", "Penghulu Mukim", "Ketua Kaum"], "jawapan": "Pembesar Empat Lipatan"},
        {"soalan": "Apakah sistem politik yang diamalkan oleh Kesultanan Johor Riau?", "pilihan": ["Demokrasi berparlimen", "Teokrasi", "Pemerintahan beraja", "Feudalisme"], "jawapan": "Pemerintahan beraja"},
        {"soalan": "Apakah nama dua pusat utama Kesultanan Johor Riau selepas kejatuhan Melaka?", "pilihan": ["Pekan dan Rembau", "Batu Sawar dan Riau", "Lingga dan Pahang", "Tumasik dan Bentan"], "jawapan": "Batu Sawar dan Riau"},
        {"soalan": "Apakah maksud 'rakyat dagang' dalam konteks Kesultanan Johor Riau?", "pilihan": ["Rakyat biasa", "Golongan pedagang luar", "Orang suruhan istana", "Petani dan nelayan"], "jawapan": "Golongan pedagang luar"},
        {"soalan": "Apakah yang dimaksudkan dengan 'naungan Belanda' terhadap Johor Riau?", "pilihan": ["Dijajah sepenuhnya", "Kerjasama politik dan perdagangan", "Gabungan ketenteraan", "Serangan diplomatik"], "jawapan": "Kerjasama politik dan perdagangan"},
        {"soalan": "Apakah tujuan utama Johor Riau menjalin hubungan dengan Belanda?", "pilihan": ["Menguasai Acheh", "Membalas dendam terhadap Siam", "Menentang Portugis di Melaka", "Mendapat bekalan senjata"], "jawapan": "Menentang Portugis di Melaka"},
        {"soalan": "Kesultanan Johor Riau wujud pada kurun ke-", "pilihan": ["14", "15", "16", "17"], "jawapan": "16"},
        {"soalan": "Mengapakah Riau menjadi penting dalam Kesultanan Johor Riau?", "pilihan": ["Sebagai pusat agama", "Pusat perindustrian", "Pusat perdagangan dan politik", "Tapak pelancongan"], "jawapan": "Pusat perdagangan dan politik"},
        {"soalan": "Siapakah pembesar yang memainkan peranan penting dalam pentadbiran?", "pilihan": ["Temenggung", "Datuk Bandar", "Syahbandar", "Maharaja Lela"], "jawapan": "Temenggung"},
        {"soalan": "Sistem pembesar empat lipatan merangkumi Bendahara, Temenggung, Laksamana dan...", "pilihan": ["Syahbandar", "Penghulu", "Raja Muda", "Penghulu Bendahari"], "jawapan": "Syahbandar"},
        {"soalan": "Apakah peranan utama Syahbandar?", "pilihan": ["Menguruskan tentera", "Menjaga urusan perdagangan", "Menentukan hukuman", "Menguruskan agama"], "jawapan": "Menjaga urusan perdagangan"},
        {"soalan": "Apakah sumber ekonomi penting di Johor Riau?", "pilihan": ["Petroleum", "Perdagangan dan pertanian", "Pembuatan tekstil", "Perlombongan emas"], "jawapan": "Perdagangan dan pertanian"},
        {"soalan": "Kepulauan Lingga dan Riau berada dalam kawasan pemerintahan...", "pilihan": ["Portugis", "Belanda", "Kesultanan Johor Riau", "Kesultanan Acheh"], "jawapan": "Kesultanan Johor Riau"},
        {"soalan": "Kesultanan Johor Riau turut dikenali dengan nama...", "pilihan": ["Johor Lama", "Johor Baru", "Empayar Johor Riau Lingga", "Kesultanan Temasik"], "jawapan": "Empayar Johor Riau Lingga"},
        {"soalan": "Apakah yang menyebabkan kelemahan Kesultanan Johor Riau pada akhir abad ke-18?", "pilihan": ["Kejatuhan ekonomi", "Serangan Siam", "Campur tangan kuasa asing", "Kemarau panjang"], "jawapan": "Campur tangan kuasa asing"},
        {"soalan": "Apakah antara bukti hubungan erat antara Johor Riau dan Belanda?", "pilihan": ["Perjanjian perdagangan", "Perkahwinan diraja", "Hubungan ketenteraan", "Gabungan kuasa laut"], "jawapan": "Perjanjian perdagangan"},
        {"soalan": "Apakah gelaran untuk pemerintah Johor Riau?", "pilihan": ["Datuk", "Sultan", "Maharaja", "Raja"], "jawapan": "Sultan"},
        {"soalan": "Peristiwa penting yang menunjukkan kerjasama Johor Riau dan Belanda ialah...", "pilihan": ["Perjanjian Pangkor", "Serangan ke atas Melaka", "Perjanjian Inggeris-Belanda", "Pemecahan kesultanan"], "jawapan": "Serangan ke atas Melaka"},
        {"soalan": "Mengapakah Johor Riau dianggap sebagai waris Kesultanan Melaka?", "pilihan": ["Sama lokasi", "Sultan berasal dari Melaka", "Rakyat Melaka berhijrah ke Johor", "Melaka menyerahkan kuasa kepada Johor"], "jawapan": "Sultan berasal dari Melaka"},
        {"soalan": "Pulau Lingga menjadi pusat pemerintahan pada...", "pilihan": ["Akhir kurun ke-17", "Awal kurun ke-18", "Pertengahan kurun ke-19", "Kurun ke-15"], "jawapan": "Awal kurun ke-18"},
        {"soalan": "Siapakah tokoh penting Kesultanan Johor Riau yang mengukuhkan pentadbiran?", "pilihan": ["Bendahara Tun Abdul Jalil", "Temenggung Daeng Ibrahim", "Laksamana Hang Tuah", "Datuk Maharaja Lela"], "jawapan": "Bendahara Tun Abdul Jalil"},
        {"soalan": "Apa kesan campur tangan British dan Belanda terhadap Johor Riau?", "pilihan": ["Penyatuan Johor dan Melaka", "Kemerdekaan lebih awal", "Perpecahan Empayar", "Pengukuhan ekonomi"], "jawapan": "Perpecahan Empayar"},
        {"soalan": "Perpecahan Empayar Johor Riau berlaku pada tahun...", "pilihan": ["1819", "1824", "1841", "1874"], "jawapan": "1824"},
        {"soalan": "Perjanjian Inggeris-Belanda 1824 menyebabkan...", "pilihan": ["Pemulihan Johor Riau", "Pembentukan kerajaan baharu", "Pembahagian wilayah kuasa", "Kemerdekaan Singapura"], "jawapan": "Pembahagian wilayah kuasa"},
        {"soalan": "Selepas Perjanjian 1824, wilayah Johor moden berada di bawah pengaruh...", "pilihan": ["Belanda", "Sepanyol", "British", "Portugis"], "jawapan": "British"},
        {"soalan": "Singapura diserahkan kepada British oleh...", "pilihan": ["Sultan Mahmud", "Raja Hussein", "Temenggung Abdul Rahman", "Sultan Ali"], "jawapan": "Temenggung Abdul Rahman"},
        {"soalan": "Kegiatan ekonomi utama masyarakat Johor Riau ialah...", "pilihan": ["Perdagangan maritim", "Pembalakan", "Perikanan sahaja", "Pertanian sahaja"], "jawapan": "Perdagangan maritim"},
        {"soalan": "Apakah bentuk pentadbiran Kesultanan Johor Riau?", "pilihan": ["Pemerintahan Beraja Berperlembagaan", "Pemerintahan Beraja Mutlak", "Pemerintahan Demokrasi", "Pemerintahan Feudal Eropah"], "jawapan": "Pemerintahan Beraja Mutlak"}
    ],
  'Bab 7': [
        {"soalan": "Siapakah pengasas Kesultanan Pahang?", "pilihan": ["Sultan Mansur Shah", "Raja Muhammad", "Raja Abdul Jalil", "Sultan Zainal Abidin"], "jawapan": "Raja Muhammad"},
        {"soalan": "Sultan pertama Kesultanan Perak ialah...", "pilihan": ["Sultan Muzaffar Shah", "Sultan Mahmud Shah", "Sultan Ahmad Tajuddin", "Sultan Mansur Shah"], "jawapan": "Sultan Muzaffar Shah"},
        {"soalan": "Asal-usul Kesultanan Perak berkait rapat dengan...", "pilihan": ["Kesultanan Melaka", "Kesultanan Johor", "Kesultanan Brunei", "Kesultanan Acheh"], "jawapan": "Kesultanan Melaka"},
        {"soalan": "Sultan pertama Kesultanan Terengganu ialah...", "pilihan": ["Sultan Zainal Abidin I", "Sultan Ahmad Tajuddin", "Sultan Mansur Shah", "Sultan Muzaffar Shah"], "jawapan": "Sultan Zainal Abidin I"},
        {"soalan": "Siapakah yang menubuhkan Kesultanan Selangor?", "pilihan": ["Raja Lumu", "Raja Abdullah", "Sultan Mansur Shah", "Raja Abdul Samad"], "jawapan": "Raja Lumu"},
        {"soalan": "Sultan pertama Kesultanan Selangor dikenali sebagai...", "pilihan": ["Sultan Salehuddin", "Sultan Iskandar", "Sultan Abdul Samad", "Sultan Alauddin"], "jawapan": "Sultan Salehuddin"},
        {"soalan": "Pahang menjadi wilayah Kesultanan Johor sebelum menjadi...", "pilihan": ["Kesultanan berdaulat", "Sebahagian Perak", "Wilayah Brunei", "Negeri Acheh"], "jawapan": "Kesultanan berdaulat"},
        {"soalan": "Perak terkenal dengan hasil sumber alam seperti...", "pilihan": ["Bijih timah", "Emas", "Petroleum", "Kayu balak"], "jawapan": "Bijih timah"},
        {"soalan": "Kesultanan Terengganu terletak di...", "pilihan": ["Pantai Timur Semenanjung", "Utara Semenanjung", "Borneo", "Pantai Barat Semenanjung"], "jawapan": "Pantai Timur Semenanjung"},
        {"soalan": "Kesultanan Selangor berkembang hasil daripada hubungan dengan...", "pilihan": ["Bugis", "Minangkabau", "Jawa", "Siam"], "jawapan": "Bugis"},
        {"soalan": "Sultan Zainal Abidin I merupakan putera kepada...", "pilihan": ["Raja Bugis", "Sultan Johor", "Sultan Pahang", "Sultan Perak"], "jawapan": "Sultan Johor"},
        {"soalan": "Apakah sumbangan penting Kesultanan Pahang kepada Alam Melayu?", "pilihan": ["Pusat perdagangan emas", "Kubu pertahanan Portugis", "Pelabuhan bebas cukai", "Pusat penyebaran agama Buddha"], "jawapan": "Pusat perdagangan emas"},
        {"soalan": "Kesultanan Perak diasaskan selepas kejatuhan...", "pilihan": ["Melaka", "Acheh", "Brunei", "Srivijaya"], "jawapan": "Melaka"},
        {"soalan": "Apakah peranan Bugis dalam Kesultanan Selangor?", "pilihan": ["Menjadi pembesar", "Menjadi musuh", "Menyerang Melaka", "Menghapuskan raja"], "jawapan": "Menjadi pembesar"},
        {"soalan": "Raja Lumu diangkat menjadi Sultan Selangor oleh...", "pilihan": ["Sultan Perak", "Sultan Johor", "Pembesar Bugis", "Sultan Brunei"], "jawapan": "Sultan Perak"},
        {"soalan": "Nama Sultan Salehuddin diambil selepas ditabalkan sebagai...", "pilihan": ["Sultan Selangor", "Sultan Johor", "Raja Perak", "Sultan Terengganu"], "jawapan": "Sultan Selangor"},
        {"soalan": "Terengganu mencapai kemajuan dari segi...", "pilihan": ["Pendidikan agama", "Perindustrian", "Pertahanan laut", "Pertanian moden"], "jawapan": "Pendidikan agama"},
        {"soalan": "Apakah bentuk pentadbiran di Kesultanan Melayu?", "pilihan": ["Beraja", "Demokrasi", "Republik", "Oligarki"], "jawapan": "Beraja"},
        {"soalan": "Kesultanan Pahang mempunyai hubungan erat dengan...", "pilihan": ["Kesultanan Johor", "Kesultanan Perak", "Kesultanan Acheh", "Kesultanan Pattani"], "jawapan": "Kesultanan Johor"},
        {"soalan": "Kesultanan Perak diasaskan oleh putera...", "pilihan": ["Sultan Mahmud Shah", "Sultan Ahmad Tajuddin", "Sultan Ibrahim Shah", "Sultan Alauddin Riayat Shah"], "jawapan": "Sultan Mahmud Shah"},
        {"soalan": "Apakah kesan kedatangan Bugis ke Selangor?", "pilihan": ["Menstabilkan politik", "Merebut takhta", "Menjadi penjajah", "Menghapuskan Melayu"], "jawapan": "Menstabilkan politik"},
        {"soalan": "Kesultanan Terengganu berkembang di bawah pimpinan...", "pilihan": ["Sultan Zainal Abidin II", "Sultan Mahmud Shah", "Raja Ahmad", "Sultan Salehuddin"], "jawapan": "Sultan Zainal Abidin II"},
        {"soalan": "Kesultanan Melayu Pahang ditubuhkan selepas kejatuhan...", "pilihan": ["Melaka", "Johor", "Perak", "Brunei"], "jawapan": "Melaka"},
        {"soalan": "Kesultanan Perak terkenal dengan perdagangan...", "pilihan": ["Bijih timah", "Rempah ratus", "Kayu gaharu", "Kopi"], "jawapan": "Bijih timah"},
        {"soalan": "Keturunan raja Kesultanan Terengganu berasal dari...", "pilihan": ["Johor", "Acheh", "Brunei", "Minangkabau"], "jawapan": "Johor"},
        {"soalan": "Siapakah yang memperkenalkan undang-undang di Kesultanan Terengganu?", "pilihan": ["Sultan Zainal Abidin III", "Sultan Ahmad Tajuddin", "Sultan Alauddin", "Raja Lumu"], "jawapan": "Sultan Zainal Abidin III"},
        {"soalan": "Apakah gelaran Raja Lumu selepas menjadi Sultan Selangor?", "pilihan": ["Sultan Salehuddin", "Sultan Iskandar", "Sultan Abdul Samad", "Sultan Alauddin"], "jawapan": "Sultan Salehuddin"},
        {"soalan": "Apakah hubungan Perak dan Johor dalam penubuhan negeri?", "pilihan": ["Asal keturunan diraja", "Perang saudara", "Perdagangan bebas", "Penjajahan bersama"], "jawapan": "Asal keturunan diraja"},
        {"soalan": "Terengganu menjadi negeri naungan kepada...", "pilihan": ["Siam", "British", "Belanda", "Sepanyol"], "jawapan": "Siam"},
        {"soalan": "Apakah faktor kemajuan ekonomi Perak?", "pilihan": ["Bijih timah", "Petroleum", "Perladangan teh", "Perikanan laut dalam"], "jawapan": "Bijih timah"},
        {"soalan": "Kesultanan Pahang turut dikenali sebagai...", "pilihan": ["Negeri Bertuah", "Negeri Melayu Berdaulat", "Negeri Indera Kayangan", "Negeri Sembilan"], "jawapan": "Negeri Melayu Berdaulat"},
        {"soalan": "Kesultanan Perak sering diserang oleh...", "pilihan": ["Acheh", "Siam", "Bugis", "Brunei"], "jawapan": "Acheh"},
        {"soalan": "Peranan Sultan dalam pentadbiran Kesultanan Melayu ialah sebagai...", "pilihan": ["Ketua agama", "Peniaga", "Pengrajin", "Ahli falsafah"], "jawapan": "Ketua agama"},
        {"soalan": "Sultan Perak pertama berasal dari keturunan...", "pilihan": ["Sultan Melaka", "Sultan Terengganu", "Raja Bugis", "Raja Siam"], "jawapan": "Sultan Melaka"},
        {"soalan": "Raja Lumu merupakan anak kepada...", "pilihan": ["Daeng Chelak", "Daeng Parani", "Daeng Menambun", "Daeng Merewah"], "jawapan": "Daeng Chelak"},
        {"soalan": "Kesultanan Selangor terkenal dengan...", "pilihan": ["Hubungan diplomatik dengan Bugis", "Penjajahan Belanda", "Kejatuhan Melaka", "Penentangan terhadap Siam"], "jawapan": "Hubungan diplomatik dengan Bugis"},
        {"soalan": "Siapakah Raja di Terengganu yang menerima pengaruh Islam dari Patani?", "pilihan": ["Sultan Zainal Abidin I", "Sultan Mahmud Shah", "Sultan Abdullah", "Sultan Ahmad"], "jawapan": "Sultan Zainal Abidin I"},
        {"soalan": "Apakah gelaran rasmi Raja Lumu selepas diiktiraf oleh Sultan Perak?", "pilihan": ["Sultan Selangor", "Sultan Bugis", "Sultan Terengganu", "Sultan Johor"], "jawapan": "Sultan Selangor"},
        {"soalan": "Apakah peranan penting Kesultanan Melayu dalam Alam Melayu?", "pilihan": ["Pusat pemerintahan dan penyebaran Islam", "Pusat perladangan teh", "Pusat pelancongan", "Pusat perdagangan China"], "jawapan": "Pusat pemerintahan dan penyebaran Islam"}
    ],
  'Bab 8': [
        {"soalan": "Kerajaan Kedah merupakan antara kerajaan tertua di Alam Melayu. Ia diasaskan pada abad ke-", "pilihan": ["Ke-5", "Ke-7", "Ke-9", "Ke-11"], "jawapan": "Ke-5"},
        {"soalan": "Apakah nama kerajaan awal Kedah?", "pilihan": ["Langkasuka", "Kadaram", "Chih Tu", "Temasik"], "jawapan": "Kadaram"},
        {"soalan": "Sistem pemerintahan Kedah adalah berasaskan kepada...", "pilihan": ["Demokrasi", "Raja Berperlembagaan", "Kesultanan", "Kerajaan Beraja Mutlak"], "jawapan": "Kesultanan"},
        {"soalan": "Kedah menerima pengaruh Islam melalui...", "pilihan": ["Perdagangan", "Penyebaran mubaligh Buddha", "Serangan tentera", "Penjajahan Siam"], "jawapan": "Perdagangan"},
        {"soalan": "Kelantan terkenal dengan gelaran negeri...", "pilihan": ["Serambi Mekah", "Bumi Kenyalang", "Jelapang Padi", "Cik Siti Wan Kembang"], "jawapan": "Serambi Mekah"},
        {"soalan": "Apakah sumber ekonomi utama rakyat Kelantan tradisional?", "pilihan": ["Perikanan", "Perlombongan", "Pertanian", "Perdagangan laut"], "jawapan": "Pertanian"},
        {"soalan": "Negeri Sembilan mengamalkan sistem pemerintahan...", "pilihan": ["Kesultanan", "Raja Berperlembagaan", "Demokrasi", "Adat Perpatih"], "jawapan": "Adat Perpatih"},
        {"soalan": "Gelaran pemerintah utama di Negeri Sembilan ialah...", "pilihan": ["Sultan", "Yang Dipertua", "Raja", "Yang di-Pertuan Besar"], "jawapan": "Yang di-Pertuan Besar"},
        {"soalan": "Perlis dahulu berada di bawah pentadbiran...", "pilihan": ["Kedah", "Kelantan", "Terengganu", "Selangor"], "jawapan": "Kedah"},
        {"soalan": "Apakah yang membezakan struktur pentadbiran Negeri Sembilan dengan negeri lain?", "pilihan": ["Tiada pembesar", "Tidak ada sistem beraja", "Pemilihan pemimpin secara demokrasi", "Mengamalkan sistem Luak dan Undang"], "jawapan": "Mengamalkan sistem Luak dan Undang"},
        {"soalan": "Kerajaan Kedah pernah diserang oleh tentera dari...", "pilihan": ["India", "Siam", "Melaka", "Aceh"], "jawapan": "Siam"},
        {"soalan": "Kelantan menerima Islam sejak abad ke-", "pilihan": ["Ke-10", "Ke-12", "Ke-14", "Ke-16"], "jawapan": "Ke-14"},
        {"soalan": "Perlis menjadi negeri berdaulat selepas...", "pilihan": ["Perjanjian Inggeris-Siam 1909", "Perang Dunia Kedua", "Penubuhan Malaysia", "Pembentukan Persekutuan Tanah Melayu"], "jawapan": "Perjanjian Inggeris-Siam 1909"},
        {"soalan": "Adat Perpatih di Negeri Sembilan berasal dari...", "pilihan": ["Minangkabau", "Bugis", "Jawa", "Aceh"], "jawapan": "Minangkabau"},
        {"soalan": "Siapakah yang memilih Yang di-Pertuan Besar Negeri Sembilan?", "pilihan": ["Pembesar Empat", "Undang Yang Empat", "Rakyat", "Sultan Melaka"], "jawapan": "Undang Yang Empat"},
        {"soalan": "Kelantan pernah diperintah oleh wanita yang dikenali sebagai...", "pilihan": ["Puteri Gunung Ledang", "Cik Siti Wan Kembang", "Tun Fatimah", "Siti Zubaidah"], "jawapan": "Cik Siti Wan Kembang"},
        {"soalan": "Perlis mendapat gelaran negeri beraja pada tahun...", "pilihan": ["1843", "1909", "1948", "1957"], "jawapan": "1843"},
        {"soalan": "Negeri Sembilan terdiri daripada beberapa wilayah kecil yang dikenali sebagai...", "pilihan": ["Mukim", "Jajahan", "Luak", "Daerah"], "jawapan": "Luak"},
        {"soalan": "Kedah menjadi pelabuhan entrepot yang penting kerana...", "pilihan": ["Lokasinya strategik", "Mempunyai lombong emas", "Tanahnya subur", "Penduduknya ramai"], "jawapan": "Lokasinya strategik"},
        {"soalan": "Apakah mata wang yang digunakan di Kedah zaman dahulu?", "pilihan": ["Duit Timah", "Syiling Emas", "Kain Tenunan", "Kerang"], "jawapan": "Duit Timah"},
        {"soalan": "Undang di Negeri Sembilan mengetuai...", "pilihan": ["Daerah", "Luak", "Mukim", "Jajahan"], "jawapan": "Luak"},
        {"soalan": "Apakah fungsi utama Undang di Negeri Sembilan?", "pilihan": ["Melantik pembesar", "Mengutip cukai", "Memerintah rakyat", "Melantik Yang di-Pertuan Besar"], "jawapan": "Melantik Yang di-Pertuan Besar"},
        {"soalan": "Apakah bentuk warisan budaya utama masyarakat Kelantan?", "pilihan": ["Batik", "Gamelan", "Wayang Kulit", "Silat"], "jawapan": "Wayang Kulit"},
        {"soalan": "Negeri Perlis dikenali sebagai negeri yang...", "pilihan": ["Paling kecil", "Paling maju", "Terletak di selatan", "Pernah menjadi wilayah Siam"], "jawapan": "Paling kecil"},
        {"soalan": "Sistem pemerintahan Kedah dikenali sebagai...", "pilihan": ["Monarki Mutlak", "Kesultanan Islam", "Demokrasi Terpimpin", "Adat Perpatih"], "jawapan": "Kesultanan Islam"},
        {"soalan": "Kedah mempunyai hubungan awal dengan kerajaan luar seperti...", "pilihan": ["India dan China", "Jepun dan Korea", "Mesir dan Parsi", "Turki dan Arab"], "jawapan": "India dan China"},
        {"soalan": "Kelantan merupakan sebahagian daripada...", "pilihan": ["Patani", "Langkasuka", "Majapahit", "Champa"], "jawapan": "Patani"},
        {"soalan": "Siapakah pengasas Kesultanan Perlis?", "pilihan": ["Sultan Zainal Abidin", "Sultan Ahmad Tajuddin", "Raja Long Krok", "Tuanku Syed Hussain Jamalullail"], "jawapan": "Tuanku Syed Hussain Jamalullail"},
        {"soalan": "Apakah hasil pertanian utama di Kedah?", "pilihan": ["Kelapa", "Getah", "Padi", "Kopi"], "jawapan": "Padi"},
        {"soalan": "Negeri Sembilan pernah menjadi sebahagian daripada...", "pilihan": ["Kesultanan Melaka", "Kesultanan Pahang", "Kesultanan Johor", "Kesultanan Perak"], "jawapan": "Kesultanan Johor"},
        {"soalan": "Kelantan terkenal dengan pembuatan...", "pilihan": ["Rebana", "Gendang", "Wau", "Angklung"], "jawapan": "Wau"},
        {"soalan": "Perlis mempunyai hubungan diplomatik awal dengan...", "pilihan": ["Siam", "Thailand", "China", "Aceh"], "jawapan": "Siam"},
        {"soalan": "Kelantan menerima pengaruh Islam terawal melalui...", "pilihan": ["Aceh", "India", "Arab", "Patani"], "jawapan": "Patani"},
        {"soalan": "Adat Perpatih menekankan...", "pilihan": ["Pewarisan harta melalui anak lelaki", "Kepimpinan wanita", "Pewarisan matrilineal", "Sistem feudal"], "jawapan": "Pewarisan matrilineal"},
        {"soalan": "Wilayah kecil di Negeri Sembilan yang diketuai oleh Undang dikenali sebagai...", "pilihan": ["Luak", "Daerah", "Mukim", "Jajahan"], "jawapan": "Luak"},
        {"soalan": "Sultan Kedah yang pertama ialah...", "pilihan": ["Sultan Muzaffar Shah", "Sultan Mahmud Shah", "Sultan Muhammad Jiwa", "Sultan Abdullah"], "jawapan": "Sultan Muzaffar Shah"},
        {"soalan": "Seni ukiran kayu banyak berkembang di negeri...", "pilihan": ["Kelantan", "Kedah", "Perlis", "Negeri Sembilan"], "jawapan": "Kelantan"},
        {"soalan": "Perlis diperintah oleh keturunan...", "pilihan": ["Bugis", "Melayu", "Minangkabau", "Arab"], "jawapan": "Arab"},
        {"soalan": "Kedah pernah dikenali sebagai...", "pilihan": ["Langkasuka", "Qalha", "Langkapura", "Langkawi"], "jawapan": "Qalha"},
        {"soalan": "Apakah tujuan utama pembentukan negeri-negeri Melayu seperti Kedah dan Kelantan?", "pilihan": ["Menentang penjajah", "Memajukan ekonomi", "Mewujudkan sistem pemerintahan", "Menyebar agama"], "jawapan": "Mewujudkan sistem pemerintahan"}
    ],
  'Bab 9': [
        {"soalan": "Apakah yang dimaksudkan dengan warisan?", "pilihan": ["Harta benda kerajaan", "Amalan dan nilai turun-temurun", "Kekayaan alam semula jadi", "Barang kemas lama"], "jawapan": "Amalan dan nilai turun-temurun"},
        {"soalan": "Warisan budaya boleh dibahagikan kepada dua jenis, iaitu...", "pilihan": ["Warisan sejarah dan warisan tradisi", "Warisan lama dan warisan moden", "Warisan ketara dan tidak ketara", "Warisan fizikal dan bukan fizikal"], "jawapan": "Warisan ketara dan tidak ketara"},
        {"soalan": "Contoh warisan tidak ketara ialah...", "pilihan": ["Istana", "Candi", "Pantun", "Rumah tradisional"], "jawapan": "Pantun"},
        {"soalan": "Manakah antara berikut merupakan warisan budaya ketara?", "pilihan": ["Cerita rakyat", "Pantun", "Gendang Melayu", "Masjid Zahir"], "jawapan": "Masjid Zahir"},
        {"soalan": "Tarian Mak Yong berasal dari negeri...", "pilihan": ["Kedah", "Kelantan", "Perlis", "Negeri Sembilan"], "jawapan": "Kelantan"},
        {"soalan": "Permainan tradisional congkak tergolong dalam...", "pilihan": ["Warisan tidak ketara", "Warisan fizikal", "Warisan ketara", "Warisan sejarah"], "jawapan": "Warisan ketara"},
        {"soalan": "Bahasa dan loghat negeri merupakan contoh warisan...", "pilihan": ["Ketara", "Tidak ketara", "Fizikal", "Kebendaan"], "jawapan": "Tidak ketara"},
        {"soalan": "Salah satu fungsi warisan budaya ialah...", "pilihan": ["Menghapuskan budaya asing", "Menggalakkan perpecahan kaum", "Memupuk identiti kebangsaan", "Membentuk kerajaan baharu"], "jawapan": "Memupuk identiti kebangsaan"},
        {"soalan": "Masjid Alwi merupakan warisan ketara dari negeri...", "pilihan": ["Kedah", "Kelantan", "Perlis", "Negeri Sembilan"], "jawapan": "Perlis"},
        {"soalan": "Warisan budaya penting dipelihara untuk...", "pilihan": ["Menarik pelabur asing", "Menguatkan ekonomi", "Mengekalkan jati diri bangsa", "Menentang penjajahan"], "jawapan": "Mengekalkan jati diri bangsa"},
        {"soalan": "Apakah nama alat muzik tradisional dari Kelantan?", "pilihan": ["Angklung", "Sape", "Rebana ubi", "Gambus"], "jawapan": "Rebana ubi"},
        {"soalan": "Permainan wau popular di negeri...", "pilihan": ["Negeri Sembilan", "Kedah", "Kelantan", "Perlis"], "jawapan": "Kelantan"},
        {"soalan": "Warisan budaya dari Kedah yang terkenal ialah...", "pilihan": ["Gendang Kelantan", "Rumah Panjang", "Labu Sayong", "Dondang Sayang"], "jawapan": "Labu Sayong"},
        {"soalan": "Gendang Terbangan merupakan warisan budaya dari...", "pilihan": ["Kedah", "Perak", "Negeri Sembilan", "Kelantan"], "jawapan": "Kedah"},
        {"soalan": "Negeri yang terkenal dengan Adat Perpatih ialah...", "pilihan": ["Kelantan", "Perlis", "Negeri Sembilan", "Kedah"], "jawapan": "Negeri Sembilan"},
        {"soalan": "Pantun dan syair merupakan bentuk...", "pilihan": ["Seni ukiran", "Peralatan perang", "Kesusasteraan tradisional", "Lagu rakyat"], "jawapan": "Kesusasteraan tradisional"},
        {"soalan": "Adat Perpatih diamalkan dalam masyarakat...", "pilihan": ["Patrilineal", "Matrilineal", "Feudal", "Demokratik"], "jawapan": "Matrilineal"},
        {"soalan": "Manakah antara berikut bukan warisan tidak ketara?", "pilihan": ["Cerita rakyat", "Pantun", "Tarian tradisional", "Masjid lama"], "jawapan": "Masjid lama"},
        {"soalan": "Apakah contoh warisan ketara dari Negeri Sembilan?", "pilihan": ["Rumah Gadang", "Istana Lama Seri Menanti", "Labu Sayong", "Rebana Ubi"], "jawapan": "Istana Lama Seri Menanti"},
        {"soalan": "Lagu rakyat berperanan untuk...", "pilihan": ["Melawan penjajah", "Menghibur rakyat", "Menulis sejarah", "Meningkatkan ekonomi"], "jawapan": "Menghibur rakyat"},
        {"soalan": "Apakah maksud adat dalam konteks warisan budaya?", "pilihan": ["Cara hidup moden", "Undang-undang rasmi", "Peraturan hidup turun-temurun", "Perintah raja"], "jawapan": "Peraturan hidup turun-temurun"},
        {"soalan": "Warna pakaian tradisional mencerminkan...", "pilihan": ["Kedudukan cuaca", "Status sosial dan budaya", "Keadaan ekonomi", "Umur seseorang"], "jawapan": "Status sosial dan budaya"},
        {"soalan": "Kain songket dikenali sebagai warisan dari negeri...", "pilihan": ["Kelantan", "Perlis", "Kedah", "Terengganu"], "jawapan": "Kelantan"},
        {"soalan": "Cerita rakyat seperti Sang Kancil mengandungi...", "pilihan": ["Fakta sejarah", "Nilai moral", "Arahan diraja", "Sumpahan"], "jawapan": "Nilai moral"},
        {"soalan": "Peranan seni ukiran ialah untuk...", "pilihan": ["Menambah nilai jualan", "Menghias dan simbolik budaya", "Mengukir perabot moden", "Menakutkan musuh"], "jawapan": "Menghias dan simbolik budaya"},
        {"soalan": "Gamelan merupakan alat muzik dari...", "pilihan": ["India", "Indonesia", "Thailand", "China"], "jawapan": "Indonesia"},
        {"soalan": "Rumah tradisional Melayu biasanya dibina menggunakan...", "pilihan": ["Simen", "Batu", "Kayu", "Logam"], "jawapan": "Kayu"},
        {"soalan": "Manakah antara berikut merupakan contoh cerita rakyat?", "pilihan": ["Sejarah Melayu", "Sang Kancil", "Hikayat Hang Tuah", "Kisah Nabi"], "jawapan": "Sang Kancil"},
        {"soalan": "Alat muzik rebab dimainkan dalam...", "pilihan": ["Mak Yong", "Zapin", "Silat", "Main puteri"], "jawapan": "Mak Yong"},
        {"soalan": "Ciri utama warisan budaya Melayu ialah...", "pilihan": ["Meniru budaya luar", "Mengikut perubahan zaman", "Berpegang pada adat", "Berorientasikan perniagaan"], "jawapan": "Berpegang pada adat"},
        {"soalan": "Makanan tradisional seperti laksa dan rendang dianggap sebagai...", "pilihan": ["Warisan moden", "Warisan makanan", "Warisan tidak ketara", "Warisan sejarah"], "jawapan": "Warisan tidak ketara"},
        {"soalan": "Upacara perkahwinan tradisional Melayu mengandungi...", "pilihan": ["Nilai budaya dan adat", "Perintah undang-undang", "Pengaruh luar", "Ritual luar negara"], "jawapan": "Nilai budaya dan adat"},
        {"soalan": "Manakah antara berikut menunjukkan nilai dalam warisan budaya?", "pilihan": ["Sifat hormat-menghormati", "Sikap penting diri", "Pemikiran moden", "Ketidakpatuhan"], "jawapan": "Sifat hormat-menghormati"},
        {"soalan": "Warisan budaya perlu dilestarikan untuk...", "pilihan": ["Dipamerkan di luar negara", "Meningkatkan eksport", "Generasi akan datang", "Kepentingan pelancongan sahaja"], "jawapan": "Generasi akan datang"},
        {"soalan": "Manakah antara berikut merupakan tujuan utama pementasan Mak Yong?", "pilihan": ["Menjual tiket", "Menghiburkan dan mendidik", "Mendapat anugerah", "Mencari keuntungan"], "jawapan": "Menghiburkan dan mendidik"},
        {"soalan": "Adat resam dalam masyarakat Melayu diwarisi secara...", "pilihan": ["Paksaan", "Dokumentasi rasmi", "Lisan dan amalan", "Internet"], "jawapan": "Lisan dan amalan"},
        {"soalan": "Warna merah dalam budaya tradisional Melayu sering dikaitkan dengan...", "pilihan": ["Kematian", "Keberanian dan semangat", "Kekayaan", "Kesucian"], "jawapan": "Keberanian dan semangat"},
        {"soalan": "Ciri utama bangunan tradisional Melayu ialah...", "pilihan": ["Dibina bertingkat", "Berbumbung limas", "Menggunakan konkrit", "Tingkap besar moden"], "jawapan": "Berbumbung limas"},
        {"soalan": "Manakah yang BUKAN manfaat mengekalkan warisan budaya?", "pilihan": ["Mengeratkan perpaduan", "Meningkatkan jati diri", "Mewujudkan kekeliruan budaya", "Menjadi identiti bangsa"], "jawapan": "Mewujudkan kekeliruan budaya"},
        {"soalan": "Salah satu peranan institusi keluarga dalam pemeliharaan warisan ialah...", "pilihan": ["Menyembunyikan budaya", "Mewajibkan adat", "Mewariskan nilai kepada anak-anak", "Menghapuskan tradisi"], "jawapan": "Mewariskan nilai kepada anak-anak"}
    ],
  'Bab 10': [
        {"soalan": "Sarawak dan Sabah terletak di bahagian manakah Malaysia?", "pilihan": ["Semenanjung Malaysia", "Malaysia Timur", "Malaysia Tengah", "Malaysia Barat"], "jawapan": "Malaysia Timur"},
        {"soalan": "Antara berikut, negeri yang termasuk dalam Malaysia Timur ialah...", "pilihan": ["Johor dan Pahang", "Sabah dan Sarawak", "Melaka dan Negeri Sembilan", "Perak dan Perlis"], "jawapan": "Sabah dan Sarawak"},
        {"soalan": "Siapakah pemerintah tradisional yang mengetuai masyarakat di Sarawak?", "pilihan": ["Raja", "Sultan", "Ketua Kaum", "Temenggung"], "jawapan": "Ketua Kaum"},
        {"soalan": "Sarawak terkenal dengan masyarakat berbilang kaum seperti...", "pilihan": ["Bugis dan Jawa", "Iban dan Bidayuh", "Banjar dan Minang", "Siam dan Arab"], "jawapan": "Iban dan Bidayuh"},
        {"soalan": "Apakah sistem pemerintahan tradisional di Sabah?", "pilihan": ["Kesultanan", "Raja Berperlembagaan", "Ketua Bebas", "Sistem Ketua Anak Negeri"], "jawapan": "Sistem Ketua Anak Negeri"},
        {"soalan": "Masyarakat Kadazandusun merupakan kumpulan etnik utama di negeri...", "pilihan": ["Sarawak", "Sabah", "Johor", "Kelantan"], "jawapan": "Sabah"},
        {"soalan": "Apakah bentuk kegiatan ekonomi tradisional utama di Sarawak dan Sabah?", "pilihan": ["Perikanan laut dalam", "Pertanian sara diri", "Perindustrian berat", "Pelancongan antarabangsa"], "jawapan": "Pertanian sara diri"},
        {"soalan": "Apakah jenis tanaman utama dalam kegiatan pertanian tradisional di Sabah?", "pilihan": ["Getah", "Kelapa sawit", "Padi huma", "Teh"], "jawapan": "Padi huma"},
        {"soalan": "Salah satu bentuk perniagaan tradisional di Sabah dan Sarawak ialah...", "pilihan": ["Perbankan", "Perdagangan tukar barang", "E-dagang", "Pasaraya besar"], "jawapan": "Perdagangan tukar barang"},
        {"soalan": "Apakah nama masyarakat pelaut yang terkenal di Sabah?", "pilihan": ["Kayan", "Bajau", "Iban", "Kedayan"], "jawapan": "Bajau"},
        {"soalan": "Rumah panjang adalah kediaman tradisional masyarakat...", "pilihan": ["Melanau", "Iban", "Kadazandusun", "Bidayuh"], "jawapan": "Iban"},
        {"soalan": "Masyarakat Bajau dikenali juga sebagai...", "pilihan": ["Orang Bukit", "Orang Laut", "Orang Gunung", "Orang Kampung"], "jawapan": "Orang Laut"},
        {"soalan": "Tarian tradisional Sumazau berasal daripada kaum...", "pilihan": ["Iban", "Kadazandusun", "Bidayuh", "Melanau"], "jawapan": "Kadazandusun"},
        {"soalan": "Tarian Ngajat merupakan warisan budaya...", "pilihan": ["Iban", "Kedayan", "Bajau", "Kadazan"], "jawapan": "Iban"},
        {"soalan": "Apakah keunikan sistem kepercayaan masyarakat pribumi Sabah dan Sarawak?", "pilihan": ["Animisme dan kepercayaan alam", "Monoteisme", "Atheisme", "Budhisme"], "jawapan": "Animisme dan kepercayaan alam"},
        {"soalan": "Antara berikut, manakah merupakan alat muzik tradisional Sabah dan Sarawak?", "pilihan": ["Kompang", "Gendang", "Sape", "Rebana"], "jawapan": "Sape"},
        {"soalan": "Sape sering dimainkan semasa...", "pilihan": ["Perayaan Gawai", "Hari Raya", "Thaipusam", "Pesta Tanglung"], "jawapan": "Perayaan Gawai"},
        {"soalan": "Pesta Kaamatan disambut oleh...", "pilihan": ["Orang Iban", "Orang Bajau", "Orang Kadazandusun", "Orang Melayu"], "jawapan": "Orang Kadazandusun"},
        {"soalan": "Pesta Gawai disambut untuk merayakan...", "pilihan": ["Musim menuai", "Kemenangan perang", "Perkahwinan diraja", "Musim panas"], "jawapan": "Musim menuai"},
        {"soalan": "Kegiatan membuat kraftangan terkenal di Sabah dan Sarawak termasuklah...", "pilihan": ["Perabot moden", "Tenunan songket", "Anyaman rotan", "Batik digital"], "jawapan": "Anyaman rotan"},
        {"soalan": "Apakah maksud rumah panjang dalam konteks Sarawak?", "pilihan": ["Rumah dua tingkat", "Tempat simpan senjata", "Rumah tinggalan kolonial", "Tempat tinggal beberapa keluarga dalam satu bangunan panjang"], "jawapan": "Tempat tinggal beberapa keluarga dalam satu bangunan panjang"},
        {"soalan": "Sistem kepercayaan masyarakat Iban berkait rapat dengan...", "pilihan": ["Kalendar Gregorian", "Peredaran bulan", "Roh nenek moyang", "Ilmu astronomi"], "jawapan": "Roh nenek moyang"},
        {"soalan": "Pakaian tradisional masyarakat Kadazandusun dikenali sebagai...", "pilihan": ["Baju Kurung", "Sinuangga", "Baro’t Saya", "Cheongsam"], "jawapan": "Sinuangga"},
        {"soalan": "Apakah hasil hutan utama masyarakat tradisional Sarawak?", "pilihan": ["Emas", "Petroleum", "Rotan dan damar", "Timah"], "jawapan": "Rotan dan damar"},
        {"soalan": "Di Sabah, golongan Ketua Anak Negeri memainkan peranan sebagai...", "pilihan": ["Tentera", "Pemungut cukai", "Pemimpin masyarakat", "Penasihat agama"], "jawapan": "Pemimpin masyarakat"},
        {"soalan": "Kaum Melanau terkenal dengan makanan tradisional seperti...", "pilihan": ["Lemang", "Hinava", "Umai", "Tempoyak"], "jawapan": "Umai"},
        {"soalan": "Pasar terapung di Sabah dan Sarawak biasanya berlaku di...", "pilihan": ["Pasar raya", "Sungai", "Kampung darat", "Gunung"], "jawapan": "Sungai"},
        {"soalan": "Masyarakat yang tinggal di kawasan pedalaman Sarawak biasanya bergantung kepada...", "pilihan": ["Perladangan moden", "Pertanian tradisional", "Pembalakan industri", "Nelayan komersial"], "jawapan": "Pertanian tradisional"},
        {"soalan": "Salah satu loghat tempatan yang dituturkan di Sabah ialah...", "pilihan": ["Melayu Sarawak", "Melayu Sabah", "Loghat Perak", "Loghat Kedah"], "jawapan": "Melayu Sabah"},
        {"soalan": "Apakah maksud 'bumiputera' dalam konteks Sabah dan Sarawak?", "pilihan": ["Orang asli sahaja", "Pendatang", "Penduduk asal pribumi", "Orang luar"], "jawapan": "Penduduk asal pribumi"},
        {"soalan": "Apakah peranan penting Ketua Kaum?", "pilihan": ["Mengurus pelancongan", "Menjadi guru", "Menjaga keamanan dan adat", "Menjadi ahli politik"], "jawapan": "Menjaga keamanan dan adat"},
        {"soalan": "Apakah warisan yang paling ketara dalam kehidupan masyarakat Sarawak?", "pilihan": ["Kebudayaan Cina", "Rumah panjang", "Masjid moden", "Menara komunikasi"], "jawapan": "Rumah panjang"},
        {"soalan": "Antara berikut, yang manakah bukan etnik utama Sabah?", "pilihan": ["Iban", "Kadazandusun", "Bajau", "Murut"], "jawapan": "Iban"},
        {"soalan": "Siapakah yang bertanggungjawab memimpin upacara tradisional dalam masyarakat pribumi?", "pilihan": ["Sultan", "Imam", "Ketua Adat", "Menteri"], "jawapan": "Ketua Adat"},
        {"soalan": "Tarian tradisional masyarakat Murut dikenali sebagai...", "pilihan": ["Magunatip", "Ngajat", "Sumazau", "Daling-daling"], "jawapan": "Magunatip"},
        {"soalan": "Masyarakat Kadazandusun menanam padi menggunakan kaedah...", "pilihan": ["Kebun bukit", "Padi sawah", "Tanaman hidroponik", "Pertanian berputar"], "jawapan": "Kebun bukit"},
        {"soalan": "Apakah keistimewaan Pesta Kaamatan?", "pilihan": ["Sambutan hari kemerdekaan", "Perayaan menuai padi", "Perayaan keagamaan", "Pesta makanan laut"], "jawapan": "Perayaan menuai padi"},
        {"soalan": "Apakah ciri utama seni bina rumah panjang?", "pilihan": ["Berbentuk segi empat tepat", "Panjang dan berkongsi dinding", "Berbentuk bulat", "Dibina atas tanah"], "jawapan": "Panjang dan berkongsi dinding"},
        {"soalan": "Salah satu bentuk perayaan tradisional yang unik di Sarawak ialah...", "pilihan": ["Kaamatan", "Hari Gawai", "Thaipusam", "Ponggal"], "jawapan": "Hari Gawai"}
    ],
};
