/// Soalan Kuiz Sejarah Tingkatan 1
/// Format: List<Map> untuk setiap Bab (Bab 1 hingga Bab 8)

const Map<String, List<Map<String, dynamic>>> sejarahKuiz = {
  'Bab 1': [
    {"soalan": "Zaman prasejarah merujuk kepada zaman sebelum...", "pilihan": ["Wujudnya logam", "Wujudnya sistem tulisan", "Wujudnya kerajaan", "Wujudnya agama"], "jawapan": "Wujudnya sistem tulisan"},
    {"soalan": "Zaman prasejarah terbahagi kepada berapa tahap?", "pilihan": ["Tiga", "Dua", "Empat", "Lima"], "jawapan": "Tiga"},
    {"soalan": "Apakah sumber utama kajian sejarah prasejarah?", "pilihan": ["Manuskrip lama", "Artifak dan fosil", "Surat diraja", "Lagenda rakyat"], "jawapan": "Artifak dan fosil"},
    {"soalan": "Zaman Paleolitik dikenali juga sebagai...", "pilihan": ["Zaman Batu Baru", "Zaman Logam", "Zaman Batu Lama", "Zaman Pertengahan"], "jawapan": "Zaman Batu Lama"},
    {"soalan": "Cara hidup manusia zaman Paleolitik adalah...", "pilihan": ["Bercucuk tanam", "Bertani dan menternak", "Berpindah randah", "Tinggal di kota"], "jawapan": "Berpindah randah"},
    {"soalan": "Manusia zaman Paleolitik tinggal di...", "pilihan": ["Bandar besar", "Rumah panjang", "Gua dan tepi sungai", "Kubu pertahanan"], "jawapan": "Gua dan tepi sungai"},
    {"soalan": "Alat utama yang digunakan semasa Zaman Paleolitik adalah...", "pilihan": ["Alat logam", "Alat gangsa", "Alat batu kasar", "Alat emas"], "jawapan": "Alat batu kasar"},
    {"soalan": "Zaman Mesolitik merupakan peralihan antara zaman...", "pilihan": ["Batu Baru dan Logam", "Batu Lama dan Batu Baru", "Logam dan Moden", "Purba dan Moden"], "jawapan": "Batu Lama dan Batu Baru"},
    {"soalan": "Zaman Neolitik dikenali sebagai zaman...", "pilihan": ["Batu Baru", "Batu Lama", "Logam", "Prasejarah"], "jawapan": "Batu Baru"},
    {"soalan": "Aktiviti utama manusia zaman Neolitik ialah...", "pilihan": ["Memburu dan memancing", "Bercucuk tanam dan menternak", "Menulis dan membaca", "Membina senjata api"], "jawapan": "Bercucuk tanam dan menternak"},
    {"soalan": "Apakah kelebihan alat batu zaman Neolitik berbanding zaman sebelumnya?", "pilihan": ["Lebih besar", "Lebih tajam dan licin", "Lebih murah", "Lebih berat"], "jawapan": "Lebih tajam dan licin"},
    {"soalan": "Apakah bahan yang mula digunakan pada Zaman Logam?", "pilihan": ["Kayu", "Tembaga dan gangsa", "Batu", "Pasir"], "jawapan": "Tembaga dan gangsa"},
    {"soalan": "Apakah faedah penggunaan logam dalam kehidupan zaman prasejarah?", "pilihan": ["Membuat pakaian", "Membina rumah", "Membuat senjata dan peralatan", "Membina jalan raya"], "jawapan": "Membuat senjata dan peralatan"},
    {"soalan": "Apakah aktiviti manusia zaman logam selain pertanian?", "pilihan": ["Perdagangan", "Menari", "Menulis sajak", "Bertapa"], "jawapan": "Perdagangan"},
    {"soalan": "Lokasi penemuan zaman prasejarah di Malaysia termasuk...", "pilihan": ["Putrajaya", "Gua Niah", "Bukit Jalil", "Kuala Lumpur"], "jawapan": "Gua Niah"},
    {"soalan": "Apakah maksud artifak?", "pilihan": ["Bahan semula jadi", "Tulisan purba", "Barang buatan manusia", "Fosil haiwan"], "jawapan": "Barang buatan manusia"},
    {"soalan": "Fosil merujuk kepada...", "pilihan": ["Tulisan lama", "Tumbuhan purba", "Sisa tinggalan manusia, haiwan dan tumbuhan", "Barang kemas lama"], "jawapan": "Sisa tinggalan manusia, haiwan dan tumbuhan"},
    {"soalan": "Siapakah arkeologis?", "pilihan": ["Pengkaji manuskrip", "Pengkaji zaman moden", "Pengkaji sejarah melalui tinggalan artifak", "Pengkaji cuaca"], "jawapan": "Pengkaji sejarah melalui tinggalan artifak"},
    {"soalan": "Perubahan cara hidup manusia prasejarah dipengaruhi oleh...", "pilihan": ["Perubahan iklim", "Perubahan raja", "Kedatangan penjajah", "Agama baharu"], "jawapan": "Perubahan iklim"},
    {"soalan": "Apakah kelebihan zaman Neolitik berbanding Paleolitik?", "pilihan": ["Lebih banyak fosil", "Kehidupan menetap dan bercucuk tanam", "Menemui tulisan", "Kehidupan berburu sepenuhnya"], "jawapan": "Kehidupan menetap dan bercucuk tanam"},
    {"soalan": "Mengapakah manusia zaman logam lebih maju?", "pilihan": ["Mereka lebih kuat", "Mereka lebih ramai", "Penggunaan logam memudahkan kehidupan", "Mereka tinggal di bandar"], "jawapan": "Penggunaan logam memudahkan kehidupan"},
    {"soalan": "Apakah peranan Sungai Perak dan Sungai Tembeling dalam zaman prasejarah?", "pilihan": ["Tempat mandi", "Tempat buang sampah", "Tempat tinggal dan cari makanan", "Tempat memancing sahaja"], "jawapan": "Tempat tinggal dan cari makanan"},
    {"soalan": "Apakah alat yang digunakan untuk bercucuk tanam zaman Neolitik?", "pilihan": ["Sabit batu", "Kapak tangan", "Pisau logam", "Cangkul kayu"], "jawapan": "Kapak tangan"},
    {"soalan": "Apakah ciri utama alat batu zaman Paleolitik?", "pilihan": ["Halus dan kecil", "Besar dan berat", "Kasarpemukaan dan tidak simetri", "Bersalut emas"], "jawapan": "Kasarpemukaan dan tidak simetri"},
    {"soalan": "Pakar kaji tinggalan prasejarah dikenali sebagai...", "pilihan": ["Geologis", "Antropologis", "Arkeologis", "Sejarawan"], "jawapan": "Arkeologis"},
    {"soalan": "Zaman Prasejarah berakhir apabila manusia mula...", "pilihan": ["Menanam padi", "Menulis dan merekod", "Menggunakan telefon", "Menjadi raja"], "jawapan": "Menulis dan merekod"},
    {"soalan": "Apakah keistimewaan Gua Niah?", "pilihan": ["Tempat perlindungan haiwan", "Tempat ibadat", "Penemuan rangka manusia tertua di Malaysia", "Kawasan pelancongan moden"], "jawapan": "Penemuan rangka manusia tertua di Malaysia"},
    {"soalan": "Manusia zaman prasejarah menghasilkan lukisan gua menggunakan...", "pilihan": ["Pensel", "Arang dan tanah liat", "Pen", "Dakwat kilang"], "jawapan": "Arang dan tanah liat"},
    {"soalan": "Apakah bahan bukti kewujudan zaman prasejarah?", "pilihan": ["Buku teks", "Rekod kerajaan", "Artifak dan fosil", "Akhbar lama"], "jawapan": "Artifak dan fosil"},
    {"soalan": "Apakah maksud zaman?", "pilihan": ["Masa dalam seminggu", "Peristiwa sejarah", "Tempoh masa tertentu", "Jenis alat batu"], "jawapan": "Tempoh masa tertentu"},
    {"soalan": "Zaman Logam di Malaysia dikatakan bermula sekitar tahun...", "pilihan": ["1000 SM", "100 SM", "500 M", "1500 M"], "jawapan": "1000 SM"},
    {"soalan": "Mengapakah manusia zaman prasejarah berpindah randah?", "pilihan": ["Mengelak cukai", "Mencari kawasan yang subur", "Takut haiwan", "Mahu memburu raja"], "jawapan": "Mencari kawasan yang subur"},
    {"soalan": "Apa yang dimaksudkan dengan budaya?", "pilihan": ["Seni dan muzik sahaja", "Cara hidup manusia", "Pakaian tradisional", "Makanan sahaja"], "jawapan": "Cara hidup manusia"},
    {"soalan": "Manusia zaman Neolitik sudah pandai membuat...", "pilihan": ["Kapal terbang", "Senjata api", "Tembikar", "Komputer"], "jawapan": "Tembikar"},
    {"soalan": "Alat batu zaman Neolitik lebih baik kerana...", "pilihan": ["Lebih hiasan", "Lebih mahal", "Lebih tahan lama dan halus", "Berwarna-warni"], "jawapan": "Lebih tahan lama dan halus"},
    {"soalan": "Perdagangan zaman logam berlaku melalui...", "pilihan": ["Pasar raya", "Tukar barang (barter)", "Wang kertas", "Emel"], "jawapan": "Tukar barang (barter)"},
    {"soalan": "Zaman Prasejarah menyumbang kepada...", "pilihan": ["Kemerosotan manusia", "Asal usul tamadun", "Kehilangan sejarah", "Kemusnahan bumi"], "jawapan": "Asal usul tamadun"},
    {"soalan": "Artifak yang ditemui boleh memberitahu kita tentang...", "pilihan": ["Jumlah penduduk", "Kebudayaan dan teknologi", "Warna kulit", "Gaya rambut"], "jawapan": "Kebudayaan dan teknologi"},
    {"soalan": "Kenapa sejarah prasejarah sukar dikaji?", "pilihan": ["Tiada internet", "Tiada sistem tulisan", "Tiada makanan", "Tiada manusia"], "jawapan": "Tiada sistem tulisan"}
],
  'Bab 2': [
    {"soalan": "Apakah yang dimaksudkan dengan Zaman Air Batu?", "pilihan": ["Zaman semua batu cair", "Zaman air beku sepenuhnya", "Zaman suhu bumi menurun drastik", "Zaman manusia hidup di laut"], "jawapan": "Zaman suhu bumi menurun drastik"},
    {"soalan": "Zaman Air Batu juga dikenali sebagai...", "pilihan": ["Zaman Logam", "Zaman Prasejarah", "Zaman Glasier", "Zaman Moden"], "jawapan": "Zaman Glasier"},
    {"soalan": "Zaman Air Batu berlaku kira-kira berapa juta tahun dahulu?", "pilihan": ["10 juta tahun", "2.5 juta tahun", "1 juta tahun", "0.5 juta tahun"], "jawapan": "2.5 juta tahun"},
    {"soalan": "Kesan utama Zaman Air Batu terhadap muka bumi ialah...", "pilihan": ["Peningkatan suhu", "Kemunculan lautan", "Pembentukan glasier dan perubahan paras laut", "Letusan gunung berapi"], "jawapan": "Pembentukan glasier dan perubahan paras laut"},
    {"soalan": "Apakah yang menyebabkan perubahan iklim semasa Zaman Air Batu?", "pilihan": ["Aktiviti manusia", "Letupan nuklear", "Perubahan orbit bumi", "Pembinaan empangan"], "jawapan": "Perubahan orbit bumi"},
    {"soalan": "Glasier ialah...", "pilihan": ["Gunung berapi beku", "Lautan ais cair", "Jisim besar ais yang bergerak perlahan", "Awan ais"], "jawapan": "Jisim besar ais yang bergerak perlahan"},
    {"soalan": "Apakah kesan pengecutan glasier terhadap paras laut?", "pilihan": ["Paras laut meningkat", "Paras laut tidak berubah", "Laut membeku sepenuhnya", "Laut bertukar menjadi tasik"], "jawapan": "Paras laut meningkat"},
    {"soalan": "Apakah hubungan Zaman Air Batu dengan pembentukan daratan?", "pilihan": ["Lautan menjadi daratan", "Pencairan ais membentuk tanah baru", "Peningkatan gunung berapi", "Batuan cair membeku"], "jawapan": "Pencairan ais membentuk tanah baru"},
    {"soalan": "Salah satu kesan Zaman Air Batu terhadap manusia ialah...", "pilihan": ["Hidup di bawah tanah", "Berpindah randah mengikut perubahan iklim", "Tidak perlukan makanan", "Menjadi haiwan"], "jawapan": "Berpindah randah mengikut perubahan iklim"},
    {"soalan": "Bagaimanakah manusia menyesuaikan diri dengan Zaman Air Batu?", "pilihan": ["Menggunakan kipas", "Berpakaian tebal dan tinggal di gua", "Berpindah ke laut", "Menghentikan pertanian"], "jawapan": "Berpakaian tebal dan tinggal di gua"},
    {"soalan": "Zaman Air Batu menyebabkan pembentukan laluan darat seperti...", "pilihan": ["Laluan udara", "Laluan laut dalam", "Jambatan darat Bering", "Laluan bawah tanah"], "jawapan": "Jambatan darat Bering"},
    {"soalan": "Jambatan darat Bering menghubungkan...", "pilihan": ["Asia dan Amerika Utara", "Asia dan Eropah", "Afrika dan Asia", "Australia dan Asia"], "jawapan": "Asia dan Amerika Utara"},
    {"soalan": "Apakah kesan pencairan ais kepada kawasan daratan?", "pilihan": ["Daratan menjadi padang pasir", "Daratan tenggelam", "Gunung berapi meletus", "Laut menjadi lebih cetek"], "jawapan": "Daratan tenggelam"},
    {"soalan": "Zaman Air Batu berakhir apabila...", "pilihan": ["Bumi bertukar warna", "Manusia pupus", "Suhu bumi meningkat dan ais mencair", "Gunung berapi meletus serentak"], "jawapan": "Suhu bumi meningkat dan ais mencair"},
    {"soalan": "Apakah hidupan yang masih wujud sejak Zaman Air Batu?", "pilihan": ["Dinasour", "Gajah purba", "Harimau", "Badak sumbu"], "jawapan": "Gajah purba"},
    {"soalan": "Contoh haiwan Zaman Air Batu ialah...", "pilihan": ["Mammoth", "Tyrannosaurus", "Kuda moden", "Kucing liar"], "jawapan": "Mammoth"},
    {"soalan": "Perubahan landskap semasa Zaman Air Batu termasuk...", "pilihan": ["Pembentukan awan", "Pembentukan padang pasir", "Pembentukan tasik glasier", "Pembentukan lautan kering"], "jawapan": "Pembentukan tasik glasier"},
    {"soalan": "Apakah kesan utama Zaman Air Batu terhadap flora dan fauna?", "pilihan": ["Peningkatan jumlah haiwan", "Kepupusan sesetengah spesies", "Kehadiran tumbuhan tropika", "Semua tumbuhan membeku"], "jawapan": "Kepupusan sesetengah spesies"},
    {"soalan": "Zaman Air Batu menyumbang kepada penghijrahan manusia kerana...", "pilihan": ["Wujudnya internet", "Ketakutan terhadap mamalia besar", "Mencari makanan dan kawasan lebih panas", "Menyerang kawasan lain"], "jawapan": "Mencari makanan dan kawasan lebih panas"},
    {"soalan": "Mengapakah ais di kutub tidak mencair sepenuhnya walaupun Zaman Air Batu berakhir?", "pilihan": ["Ais tidak boleh cair", "Masih terdapat kawasan sejuk ekstrem", "Tiada cahaya matahari", "Ais bertukar menjadi batu"], "jawapan": "Masih terdapat kawasan sejuk ekstrem"},
    {"soalan": "Jambatan darat yang terbentuk semasa Zaman Air Batu membolehkan...", "pilihan": ["Perdagangan moden", "Pembentukan negara", "Penghijrahan manusia dan haiwan", "Pembinaan bangunan tinggi"], "jawapan": "Penghijrahan manusia dan haiwan"},
    {"soalan": "Berapa kali Zaman Air Batu berlaku dalam sejarah bumi?", "pilihan": ["Sekali", "Dua kali", "Empat kali", "Lebih daripada sekali"], "jawapan": "Lebih daripada sekali"},
    {"soalan": "Kesan utama pencairan ais ialah...", "pilihan": ["Gunung menjadi rata", "Pembentukan awan tebal", "Kenaikan paras laut", "Kehilangan graviti"], "jawapan": "Kenaikan paras laut"},
    {"soalan": "Antara berikut, yang manakah hasil daripada Zaman Air Batu?", "pilihan": ["Penggunaan elektrik", "Pembentukan tasik", "Penulisan sejarah", "Penciptaan telefon"], "jawapan": "Pembentukan tasik"},
    {"soalan": "Apakah kawasan yang terbentuk selepas glasier mencair?", "pilihan": ["Padang pasir", "Gurun sejuk", "Lembah subur dan tasik", "Gunung berapi"], "jawapan": "Lembah subur dan tasik"},
    {"soalan": "Zaman Air Batu memberi kesan terhadap evolusi manusia kerana...", "pilihan": ["Mereka menjadi robot", "Mereka pupus", "Manusia terpaksa menyesuaikan diri", "Manusia bertukar menjadi haiwan"], "jawapan": "Manusia terpaksa menyesuaikan diri"},
    {"soalan": "Apakah yang berlaku kepada hidupan apabila suhu bumi menurun?", "pilihan": ["Hidupan membiak cepat", "Tiada kesan", "Kepupusan sesetengah spesies", "Haiwan menjadi manusia"], "jawapan": "Kepupusan sesetengah spesies"},
    {"soalan": "Zaman Air Batu juga mempengaruhi pembentukan...", "pilihan": ["Perayaan budaya", "Benua dan gunung", "Kerajaan moden", "Bangunan tinggi"], "jawapan": "Benua dan gunung"},
    {"soalan": "Apakah bentuk pemanasan global semulajadi selepas Zaman Air Batu?", "pilihan": ["Letusan matahari", "Pemanasan interglasier", "Litar elektrik", "Minyak mentah"], "jawapan": "Pemanasan interglasier"},
    {"soalan": "Apakah yang menyebabkan manusia dapat merentas benua semasa Zaman Air Batu?", "pilihan": ["Kapal layar", "Laluan bawah laut", "Jambatan darat akibat paras laut rendah", "Kapalterbang purba"], "jawapan": "Jambatan darat akibat paras laut rendah"},
    {"soalan": "Bagaimanakah Zaman Air Batu mempengaruhi bentuk muka bumi Malaysia?", "pilihan": ["Pembentukan tasik dan lembah", "Gunung berapi aktif", "Padang pasir besar", "Kawasan salji tebal"], "jawapan": "Pembentukan tasik dan lembah"},
    {"soalan": "Salah satu kawasan di Malaysia yang terkesan dari Zaman Air Batu ialah...", "pilihan": ["Tasik Chini", "Putrajaya", "Bukit Jalil", "Taman Negara"], "jawapan": "Tasik Chini"},
    {"soalan": "Apakah peranan tasik glasier terhadap hidupan?", "pilihan": ["Tempat perayaan", "Tempat berlindung", "Sumber air dan habitat", "Kawasan perangkap manusia"], "jawapan": "Sumber air dan habitat"},
    {"soalan": "Zaman Air Batu menunjukkan hubungan antara...", "pilihan": ["Manusia dan internet", "Cuaca dan telefon", "Iklim dan kelangsungan hidup", "Sungai dan bangunan"], "jawapan": "Iklim dan kelangsungan hidup"},
    {"soalan": "Manusia zaman ini berpindah ke kawasan lebih panas untuk...", "pilihan": ["Menanam pokok", "Menjual barang", "Kelangsungan hidup", "Memburu ais"], "jawapan": "Kelangsungan hidup"},
    {"soalan": "Apa yang berlaku apabila glasier menghakis permukaan bumi?", "pilihan": ["Membentuk dataran tinggi", "Membentuk lembah dan tasik", "Membentuk kawah", "Menjadikan bumi rata"], "jawapan": "Membentuk lembah dan tasik"},
    {"soalan": "Peningkatan suhu selepas Zaman Air Batu menyebabkan...", "pilihan": ["Kehilangan air", "Pembentukan hutan tropika", "Kemusnahan bumi", "Hujan beku"], "jawapan": "Pembentukan hutan tropika"},
    {"soalan": "Zaman Air Batu merupakan bukti bahawa bumi mengalami...", "pilihan": ["Peningkatan kepadatan", "Perubahan iklim yang berulang", "Kekal dalam satu keadaan", "Pemanasan global selamanya"], "jawapan": "Perubahan iklim yang berulang"}
  ],
  'Bab 3': [
    {"soalan": "Apakah maksud Zaman Prasejarah?", "pilihan": ["Zaman sebelum manusia wujud", "Zaman sebelum sistem tulisan", "Zaman selepas kemerdekaan", "Zaman logam sahaja"], "jawapan": "Zaman sebelum sistem tulisan"},
    {"soalan": "Apakah sumber utama untuk mengkaji Zaman Prasejarah?", "pilihan": ["Dokumen rasmi", "Rekod kerajaan", "Artifak dan fosil", "Lukisan moden"], "jawapan": "Artifak dan fosil"},
    {"soalan": "Apakah kaedah utama yang digunakan oleh arkeologis untuk mengkaji Zaman Prasejarah?", "pilihan": ["Kajian internet", "Ekskavasi arkeologi", "Kajian berita", "Perbualan lisan"], "jawapan": "Ekskavasi arkeologi"},
    {"soalan": "Zaman Prasejarah terbahagi kepada...", "pilihan": ["2 tahap", "3 tahap", "4 tahap", "5 tahap"], "jawapan": "3 tahap"},
    {"soalan": "Zaman Paleolitik dikenali sebagai Zaman...", "pilihan": ["Batu Baru", "Batu Lama", "Logam", "Tembaga"], "jawapan": "Batu Lama"},
    {"soalan": "Zaman Neolitik dikenali sebagai Zaman...", "pilihan": ["Gangsa", "Batu Baru", "Besi", "Batu Lama"], "jawapan": "Batu Baru"},
    {"soalan": "Apakah ciri utama alat batu zaman Paleolitik?", "pilihan": ["Halus dan simetri", "Kasar dan tidak simetri", "Diperbuat daripada logam", "Berwarna-warni"], "jawapan": "Kasar dan tidak simetri"},
    {"soalan": "Manusia zaman Paleolitik hidup secara...", "pilihan": ["Bercucuk tanam", "Berpindah randah", "Bermasyarakat moden", "Tinggal di bandar"], "jawapan": "Berpindah randah"},
    {"soalan": "Manusia zaman Neolitik mula menjalankan aktiviti...", "pilihan": ["Berburu sahaja", "Menulis buku", "Bercucuk tanam dan menternak", "Membina bangunan tinggi"], "jawapan": "Bercucuk tanam dan menternak"},
    {"soalan": "Alat batu zaman Neolitik berbeza daripada Paleolitik kerana...", "pilihan": ["Lebih ringan", "Lebih tajam dan licin", "Lebih besar", "Berwarna cerah"], "jawapan": "Lebih tajam dan licin"},
    {"soalan": "Perkampungan kekal wujud pada zaman...", "pilihan": ["Paleolitik", "Mesolitik", "Neolitik", "Logam"], "jawapan": "Neolitik"},
    {"soalan": "Apakah maksud artifak?", "pilihan": ["Lukisan semula jadi", "Tulisan lama", "Barang buatan manusia", "Batu besar"], "jawapan": "Barang buatan manusia"},
    {"soalan": "Fosil merujuk kepada...", "pilihan": ["Artifak logam", "Tinggalan hidup seperti tulang manusia atau haiwan", "Batu besar", "Tanah liat"], "jawapan": "Tinggalan hidup seperti tulang manusia atau haiwan"},
    {"soalan": "Manusia zaman logam mula pandai...", "pilihan": ["Mencipta komputer", "Membuat alat dari logam", "Menulis sistem undang-undang", "Membina empangan moden"], "jawapan": "Membuat alat dari logam"},
    {"soalan": "Apakah kelebihan penggunaan logam pada zaman prasejarah?", "pilihan": ["Lebih murah", "Tahan lama dan kuat", "Berwarna-warni", "Tidak boleh karat"], "jawapan": "Tahan lama dan kuat"},
    {"soalan": "Gua Niah merupakan penemuan penting kerana...", "pilihan": ["Terdapat tulisan lama", "Terdapat rangka manusia prasejarah", "Terdapat emas", "Terdapat senjata moden"], "jawapan": "Terdapat rangka manusia prasejarah"},
    {"soalan": "Apakah bukti wujudnya aktiviti pertanian dalam Zaman Prasejarah?", "pilihan": ["Lukisan gua", "Artifak batu", "Sisa makanan", "Peralatan bercucuk tanam"], "jawapan": "Peralatan bercucuk tanam"},
    {"soalan": "Kapak genggam digunakan pada zaman...", "pilihan": ["Mesolitik", "Paleolitik", "Neolitik", "Logam"], "jawapan": "Paleolitik"},
    {"soalan": "Manusia zaman prasejarah menggunakan lukisan gua untuk...", "pilihan": ["Menghias rumah", "Berkomunikasi", "Menakutkan haiwan", "Meniru alam"], "jawapan": "Berkomunikasi"},
    {"soalan": "Apakah tujuan utama manusia zaman prasejarah berpindah randah?", "pilihan": ["Melarikan diri dari musuh", "Mencari makanan dan tempat tinggal", "Berperang", "Menjelajah dunia"], "jawapan": "Mencari makanan dan tempat tinggal"},
    {"soalan": "Ciri-ciri kehidupan zaman Neolitik ialah...", "pilihan": ["Berburu sepenuhnya", "Tidak menetap", "Hidup berkelompok dan bercucuk tanam", "Tiada peralatan"], "jawapan": "Hidup berkelompok dan bercucuk tanam"},
    {"soalan": "Contoh alat logam ialah...", "pilihan": ["Kapak batu", "Cangkul gangsa", "Pisau kayu", "Tombak kayu"], "jawapan": "Cangkul gangsa"},
    {"soalan": "Sungai digunakan dalam Zaman Prasejarah untuk...", "pilihan": ["Bermain", "Mandi sahaja", "Sumber air dan pengangkutan", "Pembinaan empangan moden"], "jawapan": "Sumber air dan pengangkutan"},
    {"soalan": "Apakah kawasan penempatan awal manusia prasejarah?", "pilihan": ["Hutan tebal", "Kawasan pergunungan tinggi", "Gua dan tepi sungai", "Padang pasir"], "jawapan": "Gua dan tepi sungai"},
    {"soalan": "Pakaian manusia prasejarah diperbuat daripada...", "pilihan": ["Kapas", "Kulit haiwan", "Serat tiruan", "Benang nilon"], "jawapan": "Kulit haiwan"},
    {"soalan": "Apakah kepentingan api pada zaman prasejarah?", "pilihan": ["Untuk memasak dan perlindungan", "Untuk bermain", "Untuk pertunjukan", "Untuk membakar hutan"], "jawapan": "Untuk memasak dan perlindungan"},
    {"soalan": "Apakah bahan yang digunakan untuk membuat tembikar pada zaman Neolitik?", "pilihan": ["Kayu", "Batu", "Tanah liat", "Pasir laut"], "jawapan": "Tanah liat"},
    {"soalan": "Apakah faedah utama tembikar dalam kehidupan zaman prasejarah?", "pilihan": ["Sebagai senjata", "Untuk simpan makanan dan air", "Untuk perhiasan", "Untuk berniaga"], "jawapan": "Untuk simpan makanan dan air"},
    {"soalan": "Apakah ciri tembikar zaman Neolitik?", "pilihan": ["Tidak berhias", "Berhias dan kemas", "Berduri", "Diperbuat dari logam"], "jawapan": "Berhias dan kemas"},
    {"soalan": "Manusia prasejarah menghasilkan alat dengan menggunakan kaedah...", "pilihan": ["Cetakan moden", "Pukulan dan ketukan", "Laser", "Teknik digital"], "jawapan": "Pukulan dan ketukan"},
    {"soalan": "Zaman Logam bermula apabila manusia mula menggunakan...", "pilihan": ["Batu licin", "Gangsa dan besi", "Kayu keras", "Kulit pokok"], "jawapan": "Gangsa dan besi"},
    {"soalan": "Manusia zaman logam menjalankan aktiviti perdagangan melalui sistem...", "pilihan": ["Kad kredit", "Barter", "E-dagang", "Tunai"], "jawapan": "Barter"},
    {"soalan": "Apakah jenis sistem masyarakat yang wujud pada Zaman Prasejarah?", "pilihan": ["Demokrasi", "Feudal", "Patriarki dan Matriarki", "Sosialis"], "jawapan": "Patriarki dan Matriarki"},
    {"soalan": "Ciri utama masyarakat patriarki ialah...", "pilihan": ["Dipimpin oleh wanita", "Dipimpin oleh lelaki", "Tiada ketua", "Dipilih melalui undi"], "jawapan": "Dipimpin oleh lelaki"},
    {"soalan": "Apakah contoh masyarakat matriarki?", "pilihan": ["Diketuai oleh ketua lelaki", "Diketuai oleh wanita", "Tiada peraturan", "Diketuai oleh remaja"], "jawapan": "Diketuai oleh wanita"},
    {"soalan": "Lukisan gua dijumpai di kawasan...", "pilihan": ["Luar bandar", "Gunung berapi", "Gua dan dinding batu", "Hutan tebal"], "jawapan": "Gua dan dinding batu"},
    {"soalan": "Zaman Prasejarah berakhir apabila manusia mula...", "pilihan": ["Berpakaian moden", "Menggunakan tulisan", "Mencipta roda", "Membina empangan"], "jawapan": "Menggunakan tulisan"},
    {"soalan": "Manusia zaman prasejarah tinggal berdekatan sungai kerana...", "pilihan": ["Mudah untuk bersembunyi", "Sumber air dan makanan", "Mencari hiburan", "Memancing sahaja"], "jawapan": "Sumber air dan makanan"},
    {"soalan": "Zaman prasejarah membantu kita memahami...", "pilihan": ["Fiksyen moden", "Asal-usul kehidupan manusia", "Kisah dongeng", "Teknologi tinggi"], "jawapan": "Asal-usul kehidupan manusia"}
  ],
  'Bab 4': [
    {"soalan": "Apakah maksud tamadun?", "pilihan": ["Cara hidup liar", "Kehidupan moden", "Pencapaian manusia dalam pelbagai aspek", "Kehidupan dalam gua"], "jawapan": "Pencapaian manusia dalam pelbagai aspek"},
    {"soalan": "Perkataan 'tamadun' berasal daripada bahasa...", "pilihan": ["Arab", "Greek", "Sanskrit", "Latin"], "jawapan": "Arab"},
    {"soalan": "Perkataan 'madani' dalam bahasa Arab bermaksud...", "pilihan": ["Moden", "Kehidupan liar", "Kehidupan bandar", "Kehidupan desa"], "jawapan": "Kehidupan bandar"},
    {"soalan": "Perkataan 'civilization' berasal daripada bahasa...", "pilihan": ["Greek", "Latin", "Arab", "Jerman"], "jawapan": "Latin"},
    {"soalan": "Antara ciri tamadun awal ialah...", "pilihan": ["Tiada sistem tulisan", "Hidup berpindah randah", "Kehidupan menetap dan sistem organisasi", "Tiada agama"], "jawapan": "Kehidupan menetap dan sistem organisasi"},
    {"soalan": "Apakah kepentingan sistem tulisan dalam sesebuah tamadun?", "pilihan": ["Untuk hiburan", "Untuk berperang", "Untuk merekod dan menyebar ilmu", "Untuk menyanyi"], "jawapan": "Untuk merekod dan menyebar ilmu"},
    {"soalan": "Salah satu contoh tamadun awal dunia ialah...", "pilihan": ["Tamadun Melayu", "Tamadun Islam", "Tamadun Mesopotamia", "Tamadun Eropah"], "jawapan": "Tamadun Mesopotamia"},
    {"soalan": "Tamadun Mesir Purba berkembang di sungai...", "pilihan": ["Nil", "Tigris", "Euphrates", "Amazon"], "jawapan": "Nil"},
    {"soalan": "Tamadun Mesopotamia berkembang di antara sungai...", "pilihan": ["Nil dan Amazon", "Tigris dan Euphrates", "Ganges dan Indus", "Mekong dan Irrawaddy"], "jawapan": "Tigris dan Euphrates"},
    {"soalan": "Tamadun India berkembang di sekitar sungai...", "pilihan": ["Nil", "Ganges", "Indus", "Yangtze"], "jawapan": "Indus"},
    {"soalan": "Tamadun China berkembang di sungai...", "pilihan": ["Huang He", "Yangtze", "Indus", "Nil"], "jawapan": "Huang He"},
    {"soalan": "Apakah tujuan utama manusia membentuk tamadun?", "pilihan": ["Untuk berperang", "Untuk membina bangunan tinggi", "Untuk kestabilan hidup dan pembangunan masyarakat", "Untuk berpindah randah"], "jawapan": "Untuk kestabilan hidup dan pembangunan masyarakat"},
    {"soalan": "Apakah sistem pemerintahan tamadun awal?", "pilihan": ["Demokrasi moden", "Sistem beraja atau teokrasi", "Sistem pilihan raya", "Komunisme"], "jawapan": "Sistem beraja atau teokrasi"},
    {"soalan": "Siapakah yang memerintah dalam sistem teokrasi?", "pilihan": ["Rakyat biasa", "Pemimpin tentera", "Ketua agama", "Pedagang"], "jawapan": "Ketua agama"},
    {"soalan": "Apakah tujuan pembinaan kota dalam tamadun awal?", "pilihan": ["Tempat berkelah", "Tempat tinggal sementara", "Pusat pentadbiran dan keagamaan", "Tempat percutian"], "jawapan": "Pusat pentadbiran dan keagamaan"},
    {"soalan": "Apakah bahan utama yang digunakan dalam pembinaan bangunan tamadun awal?", "pilihan": ["Kayu", "Batu dan tanah liat", "Besi", "Kaca"], "jawapan": "Batu dan tanah liat"},
    {"soalan": "Tamadun Mesopotamia memperkenalkan sistem tulisan dikenali sebagai...", "pilihan": ["Hieroglif", "Rumi", "Kawi", "Cuneiform"], "jawapan": "Cuneiform"},
    {"soalan": "Tulisan tamadun Mesir Purba dikenali sebagai...", "pilihan": ["Jawi", "Cuneiform", "Hieroglif", "Latin"], "jawapan": "Hieroglif"},
    {"soalan": "Apakah fungsi ziggurat dalam tamadun Mesopotamia?", "pilihan": ["Pasar raya", "Rumah rakyat", "Kuil dan pusat pentadbiran", "Penjara"], "jawapan": "Kuil dan pusat pentadbiran"},
    {"soalan": "Piramid di Mesir Purba berfungsi sebagai...", "pilihan": ["Tempat hiburan", "Makmal", "Makam firaun", "Kedai makanan"], "jawapan": "Makam firaun"},
    {"soalan": "Sumbangan utama tamadun Mesir Purba dalam bidang perubatan ialah...", "pilihan": ["Pembedahan moden", "Ilmu anatomi dan mumia", "Antibiotik", "Hospital digital"], "jawapan": "Ilmu anatomi dan mumia"},
    {"soalan": "Apakah contoh tamadun awal di India?", "pilihan": ["Tamadun Maurya", "Tamadun Mohenjo-Daro dan Harappa", "Tamadun Gupta", "Tamadun Kalinga"], "jawapan": "Tamadun Mohenjo-Daro dan Harappa"},
    {"soalan": "Antara pencapaian tamadun India Purba ialah...", "pilihan": ["Membina internet", "Membina sistem kumbahan dan perancangan bandar", "Membina kereta", "Menulis komputer"], "jawapan": "Membina sistem kumbahan dan perancangan bandar"},
    {"soalan": "Tamadun China Purba dikenali kerana...", "pilihan": ["Penghasilan logam berat", "Rekaan elektronik", "Penciptaan kertas dan sutera", "Pemodenan pertanian"], "jawapan": "Penciptaan kertas dan sutera"},
    {"soalan": "Antara sumbangan tamadun awal kepada dunia ialah...", "pilihan": ["Teknologi nuklear", "Sistem tulisan, undang-undang dan seni bina", "Kenderaan moden", "Telefon pintar"], "jawapan": "Sistem tulisan, undang-undang dan seni bina"},
    {"soalan": "Salah satu ciri utama tamadun ialah...", "pilihan": ["Tiada masyarakat", "Tidak teratur", "Organisasi sosial yang tersusun", "Tiada pertanian"], "jawapan": "Organisasi sosial yang tersusun"},
    {"soalan": "Apakah tujuan pembahagian sosial dalam masyarakat tamadun?", "pilihan": ["Untuk menindas rakyat", "Untuk menyeragamkan kuasa", "Untuk menjamin kelangsungan sistem sosial", "Untuk menyembunyikan maklumat"], "jawapan": "Untuk menjamin kelangsungan sistem sosial"},
    {"soalan": "Apakah peranan agama dalam tamadun awal?", "pilihan": ["Tiada peranan", "Sebagai hiburan", "Sebagai asas nilai dan pemerintahan", "Untuk perniagaan"], "jawapan": "Sebagai asas nilai dan pemerintahan"},
    {"soalan": "Tamadun awal biasanya berkembang di kawasan...", "pilihan": ["Gurun", "Tepi laut", "Lembah sungai", "Gunung tinggi"], "jawapan": "Lembah sungai"},
    {"soalan": "Tamadun awal berkembang kerana adanya...", "pilihan": ["Internet", "Pertanian dan sumber air", "Minyak mentah", "Emas"], "jawapan": "Pertanian dan sumber air"},
    {"soalan": "Antara pencapaian teknologi dalam tamadun awal ialah...", "pilihan": ["Robotik", "Penjana elektrik", "Roda dan bajak", "Kapal terbang"], "jawapan": "Roda dan bajak"},
    {"soalan": "Kod undang-undang Hammurabi berasal dari tamadun...", "pilihan": ["Mesir Purba", "India Purba", "China Purba", "Mesopotamia"], "jawapan": "Mesopotamia"},
    {"soalan": "Ciri sistem tulisan tamadun awal ialah...", "pilihan": ["Simbol dan gambar", "Huruf rumi", "Abjad moden", "Tulisan digital"], "jawapan": "Simbol dan gambar"},
    {"soalan": "Apakah kesan sistem tulisan kepada sejarah manusia?", "pilihan": ["Tiada kesan", "Menghentikan tradisi lisan", "Merevolusi cara merekod dan warisan ilmu", "Menghapus budaya"], "jawapan": "Merevolusi cara merekod dan warisan ilmu"},
    {"soalan": "Apakah kepentingan tamadun dalam pembinaan negara?", "pilihan": ["Menghapus budaya", "Menggalakkan peperangan", "Membentuk jati diri dan kemajuan masyarakat", "Menolak teknologi"], "jawapan": "Membentuk jati diri dan kemajuan masyarakat"},
    {"soalan": "Apakah contoh bangunan keagamaan dalam tamadun India Purba?", "pilihan": ["Ziggurat", "Piramid", "Stupa", "Pagoda"], "jawapan": "Stupa"},
    {"soalan": "Penciptaan kalendar oleh tamadun awal membantu dalam bidang...", "pilihan": ["Ekonomi sahaja", "Pertanian dan keagamaan", "Perubatan", "Perdagangan luar"], "jawapan": "Pertanian dan keagamaan"},
    {"soalan": "Apakah bentuk seni yang dikembangkan dalam tamadun awal?", "pilihan": ["Seni digital", "Seni lukis gua", "Seni ukiran dan binaan", "Seni persembahan moden"], "jawapan": "Seni ukiran dan binaan"},
    {"soalan": "Mengapakah tamadun awal penting dalam memahami sejarah?", "pilihan": ["Ia tidak penting", "Membantu membina negara moden", "Untuk menentang sejarah", "Untuk menghapus masa silam"], "jawapan": "Membantu membina negara moden"}
  ],
  'Bab 5': [
    {"soalan": "Apakah maksud tamadun dari segi bahasa?", "pilihan": ["Kemajuan", "Kemasyarakatan", "Perdagangan", "Perindustrian"], "jawapan": "Kemajuan"},
    {"soalan": "Di manakah terletaknya tamadun Mesopotamia?", "pilihan": ["Sungai Nil", "Sungai Indus", "Sungai Huang He", "Sungai Tigris dan Euphrates"], "jawapan": "Sungai Tigris dan Euphrates"},
    {"soalan": "Apakah sistem tulisan yang digunakan oleh tamadun Mesopotamia?", "pilihan": ["Hieroglif", "Kuneiform", "Piktograf", "Rumi"], "jawapan": "Kuneiform"},
    {"soalan": "Siapakah pengasas Tamadun Mesir Purba?", "pilihan": ["Firaun Narmer", "Hammurabi", "Sargon", "Ashurbanipal"], "jawapan": "Firaun Narmer"},
    {"soalan": "Apakah sungai yang penting bagi Tamadun Mesir Purba?", "pilihan": ["Sungai Indus", "Sungai Huang He", "Sungai Nil", "Sungai Amazon"], "jawapan": "Sungai Nil"},
    {"soalan": "Apakah sistem tulisan dalam Tamadun Mesir Purba?", "pilihan": ["Tulisan Rumi", "Tulisan Kawi", "Tulisan Hieroglif", "Tulisan Brahmi"], "jawapan": "Tulisan Hieroglif"},
    {"soalan": "Apakah pusat tamadun Mesopotamia yang terkenal?", "pilihan": ["Thebes", "Babylon", "Memphis", "Harappa"], "jawapan": "Babylon"},
    {"soalan": "Apakah hasil utama pertanian di Mesopotamia?", "pilihan": ["Padi", "Gandum dan barli", "Jagung", "Kacang soya"], "jawapan": "Gandum dan barli"},
    {"soalan": "Salah satu undang-undang terkenal dalam tamadun Mesopotamia ialah...", "pilihan": ["Kod Hammurabi", "Undang-undang Manu", "Undang-undang Qin", "Undang-undang Narmer"], "jawapan": "Kod Hammurabi"},
    {"soalan": "Apakah sistem pemerintahan dalam Tamadun Mesir Purba?", "pilihan": ["Demokrasi", "Teokrasi", "Aristokrasi", "Feudalisme"], "jawapan": "Teokrasi"},
    {"soalan": "Di manakah Tamadun Indus berkembang?", "pilihan": ["Pakistan dan barat laut India", "China", "Mesir", "Iraq"], "jawapan": "Pakistan dan barat laut India"},
    {"soalan": "Apakah dua bandar utama dalam Tamadun Indus?", "pilihan": ["Babylon dan Ur", "Harappa dan Mohenjo-Daro", "Thebes dan Memphis", "Luoyang dan Anyang"], "jawapan": "Harappa dan Mohenjo-Daro"},
    {"soalan": "Apakah sistem tulisan dalam Tamadun Indus?", "pilihan": ["Belum dapat dikenal pasti sepenuhnya", "Hieroglif", "Kuneiform", "Tulisan Cina"], "jawapan": "Belum dapat dikenal pasti sepenuhnya"},
    {"soalan": "Apakah bukti menunjukkan Tamadun Indus mempunyai perancangan bandar yang baik?", "pilihan": ["Makam batu", "Sistem kumbahan terancang", "Candi besar", "Tembok kota"], "jawapan": "Sistem kumbahan terancang"},
    {"soalan": "Apakah sungai utama dalam Tamadun China Purba?", "pilihan": ["Sungai Tigris", "Sungai Indus", "Sungai Huang He", "Sungai Nil"], "jawapan": "Sungai Huang He"},
    {"soalan": "Apakah sistem tulisan dalam Tamadun China Purba?", "pilihan": ["Hieroglif", "Tulisan paku", "Tulisan ideogram", "Tulisan Jawi"], "jawapan": "Tulisan ideogram"},
    {"soalan": "Apakah sistem pemerintahan dalam Tamadun China Purba?", "pilihan": ["Sultan", "Maharaja", "Firaun", "Presiden"], "jawapan": "Maharaja"},
    {"soalan": "Apakah konsep Mandat Syurga dalam Tamadun China Purba?", "pilihan": ["Kuasa suci dari rakyat", "Hak untuk menakluk", "Hak pemerintahan diberi oleh syurga", "Kebebasan beragama"], "jawapan": "Hak pemerintahan diberi oleh syurga"},
    {"soalan": "Apakah agama utama dalam Tamadun Mesir Purba?", "pilihan": ["Islam", "Hindu", "Penyembahan dewa-dewa", "Buddha"], "jawapan": "Penyembahan dewa-dewa"},
    {"soalan": "Apakah ciri-ciri tamadun?", "pilihan": ["Pertanian dan hutan", "Kehidupan nomad", "Organisasi sosial, sistem tulisan, perundangan", "Berburu dan meramu"], "jawapan": "Organisasi sosial, sistem tulisan, perundangan"},
    {"soalan": "Mengapakah sungai penting dalam perkembangan tamadun awal?", "pilihan": ["Untuk pertahanan", "Sebagai laluan pelancong", "Membekalkan air dan menyuburkan tanah", "Untuk keagamaan"], "jawapan": "Membekalkan air dan menyuburkan tanah"},
    {"soalan": "Siapakah tokoh yang memperkenalkan Kod Hammurabi?", "pilihan": ["Sargon", "Ashurbanipal", "Narmer", "Hammurabi"], "jawapan": "Hammurabi"},
    {"soalan": "Apakah keunikan sistem bandar dalam Tamadun Indus?", "pilihan": ["Bangunan batu besar", "Pusat ibadah utama", "Bandar terancang dengan grid", "Laluan rahsia bawah tanah"], "jawapan": "Bandar terancang dengan grid"},
    {"soalan": "Apakah bahan utama pembinaan piramid di Mesir?", "pilihan": ["Batu pasir", "Granit", "Batu kapur", "Simen"], "jawapan": "Batu kapur"},
    {"soalan": "Apakah fungsi piramid dalam Tamadun Mesir Purba?", "pilihan": ["Rumah ibadat", "Tempat tinggal", "Makam firaun", "Perpustakaan"], "jawapan": "Makam firaun"},
    {"soalan": "Apakah ciptaan penting Tamadun China Purba?", "pilihan": ["Percetakan blok kayu", "Kod undang-undang", "Alat besi", "Tulisan paku"], "jawapan": "Percetakan blok kayu"},
    {"soalan": "Apakah maksud hieroglif?", "pilihan": ["Tulisan suci", "Tulisan gambar", "Tulisan rakyat", "Tulisan kayu"], "jawapan": "Tulisan gambar"},
    {"soalan": "Apakah nama Maharaja pertama China yang menyatukan negara?", "pilihan": ["Qin Shi Huang", "Hammurabi", "Sargon", "Narmer"], "jawapan": "Qin Shi Huang"},
    {"soalan": "Apakah sistem yang digunakan untuk memilih pemimpin dalam tamadun awal China?", "pilihan": ["Undi rakyat", "Warisan keluarga diraja", "Pemilihan tentera", "Pilihan ketua agama"], "jawapan": "Warisan keluarga diraja"},
    {"soalan": "Apakah bahan utama tulisan kuneiform ditulis?", "pilihan": ["Kulit kayu", "Papirus", "Tanah liat", "Batu"], "jawapan": "Tanah liat"},
    {"soalan": "Apakah sumbangan utama Tamadun Indus kepada dunia moden?", "pilihan": ["Agama Buddha", "Sistem kumbahan", "Seni bina batu besar", "Alat besi"], "jawapan": "Sistem kumbahan"},
    {"soalan": "Apakah peranan firaun dalam Tamadun Mesir?", "pilihan": ["Ketua agama sahaja", "Panglima perang sahaja", "Raja dan ketua agama", "Pegawai perbendaharaan"], "jawapan": "Raja dan ketua agama"},
    {"soalan": "Apakah antara hasil seni Tamadun Mesir Purba?", "pilihan": ["Ukiran batu bersurat", "Patung Buddha", "Topeng emas firaun", "Kipas logam"], "jawapan": "Topeng emas firaun"},
    {"soalan": "Apakah fungsi sungai dalam kehidupan masyarakat tamadun awal?", "pilihan": ["Pusat upacara", "Laluan perdagangan dan pertanian", "Perkuburan", "Tempat sukan"], "jawapan": "Laluan perdagangan dan pertanian"},
    {"soalan": "Tamadun Mesir Purba berkembang di sepanjang...", "pilihan": ["Sungai Indus", "Sungai Amazon", "Sungai Nil", "Sungai Mekong"], "jawapan": "Sungai Nil"},
    {"soalan": "Apakah maksud tamadun dari segi istilah?", "pilihan": ["Kemunduran sesebuah masyarakat", "Kemajuan sistem politik dan ekonomi", "Kehidupan luar bandar", "Kemasyarakatan luar bandar"], "jawapan": "Kemajuan sistem politik dan ekonomi"},
    {"soalan": "Apakah bahan utama pembinaan tembok besar China?", "pilihan": ["Bata dan tanah", "Kayu", "Besi", "Batu marmar"], "jawapan": "Bata dan tanah"},
    {"soalan": "Apakah konsep penting dalam sistem kepercayaan Mesir Purba?", "pilihan": ["Reinkarnasi", "Akhirat", "Mandat syurga", "Syurga Neraka"], "jawapan": "Akhirat"},
    {"soalan": "Apakah hasil pertanian utama Tamadun China Purba?", "pilihan": ["Jagung", "Gandum", "Barli", "Padi"], "jawapan": "Padi"},
    {"soalan": "Apakah nama alat muzik yang digunakan dalam upacara keagamaan tamadun awal?", "pilihan": ["Erhu", "Lira", "Seruling", "Gong"], "jawapan": "Gong"}
  ],
  'Bab 6': [
    {"soalan": "Apakah maksud 'tamadun' dalam konteks Yunani dan Rom?", "pilihan": ["Kehidupan di kampung", "Perkembangan dari segi rohani sahaja", "Pencapaian dalam pelbagai aspek kehidupan", "Kehidupan berasaskan pertanian semata-mata"], "jawapan": "Pencapaian dalam pelbagai aspek kehidupan"},
    {"soalan": "Apakah bentuk pemerintahan yang paling awal diamalkan di Yunani?", "pilihan": ["Demokrasi", "Monarki", "Oligarki", "Republik"], "jawapan": "Monarki"},
    {"soalan": "Negara kota Yunani dikenali sebagai apa?", "pilihan": ["Provinsi", "Negara bangsa", "Polis", "Daerah"], "jawapan": "Polis"},
    {"soalan": "Athens terkenal kerana mengamalkan sistem pemerintahan...", "pilihan": ["Monarki", "Demokrasi", "Feudal", "Teokrasi"], "jawapan": "Demokrasi"},
    {"soalan": "Sparta lebih menumpukan perhatian kepada...", "pilihan": ["Kesenian", "Ketenteraan", "Falsafah", "Ekonomi"], "jawapan": "Ketenteraan"},
    {"soalan": "Siapakah ahli falsafah Yunani yang terkenal dengan kaedah soal jawab?", "pilihan": ["Socrates", "Plato", "Aristotle", "Pythagoras"], "jawapan": "Socrates"},
    {"soalan": "Apakah sumbangan besar Plato dalam bidang pendidikan?", "pilihan": ["Akademi", "Lyceum", "Demokrasi", "Kedoktoran"], "jawapan": "Akademi"},
    {"soalan": "Apakah nama karya terkenal Aristotle?", "pilihan": ["Republik", "Politik", "Etika", "Perlembagaan"], "jawapan": "Politik"},
    {"soalan": "Apakah pusat tamadun Rom?", "pilihan": ["Athens", "Sparta", "Rome", "Delphi"], "jawapan": "Rome"},
    {"soalan": "Apakah bentuk pemerintahan awal di Rom sebelum empayar?", "pilihan": ["Demokrasi", "Republik", "Feudal", "Teokrasi"], "jawapan": "Republik"},
    {"soalan": "Siapakah tokoh penting dalam perluasan Empayar Rom?", "pilihan": ["Alexander the Great", "Socrates", "Julius Caesar", "Leonidas"], "jawapan": "Julius Caesar"},
    {"soalan": "Apakah nama undang-undang tertulis Rom?", "pilihan": ["Undang-undang Hammurabi", "12 Tablets", "Perlembagaan Athens", "Kod Justinian"], "jawapan": "12 Tablets"},
    {"soalan": "Sumbangan seni bina utama Rom ialah...", "pilihan": ["Menara", "Kuil", "Colosseum", "Acropolis"], "jawapan": "Colosseum"},
    {"soalan": "Tamadun Rom banyak menerima pengaruh daripada...", "pilihan": ["Mesir", "India", "Yunani", "China"], "jawapan": "Yunani"},
    {"soalan": "Apakah tujuan utama pembinaan jalan raya dalam tamadun Rom?", "pilihan": ["Perdagangan", "Perlancongan", "Ketenteraan", "Hubungan diplomatik"], "jawapan": "Ketenteraan"},
    {"soalan": "Tamadun Yunani terkenal dalam bidang...", "pilihan": ["Astronomi", "Pertanian", "Falsafah", "Kewangan"], "jawapan": "Falsafah"},
    {"soalan": "Salah satu sumbangan tamadun Yunani kepada dunia moden ialah...", "pilihan": ["Peta dunia", "Sistem kasta", "Demokrasi", "Feudalisme"], "jawapan": "Demokrasi"},
    {"soalan": "Manakah antara berikut merupakan ahli sains Yunani?", "pilihan": ["Plato", "Socrates", "Archimedes", "Julius Caesar"], "jawapan": "Archimedes"},
    {"soalan": "Apakah maksud 'Senat' dalam konteks Rom?", "pilihan": ["Dewan Kehakiman", "Dewan Perundangan", "Dewan Rakyat", "Dewan Tentera"], "jawapan": "Dewan Perundangan"},
    {"soalan": "Salah satu pencapaian tamadun Rom dalam kejuruteraan ialah...", "pilihan": ["Menara miring", "Jambatan gantung", "Aqueduct", "Ziggurat"], "jawapan": "Aqueduct"},
    {"soalan": "Siapakah yang menubuhkan Empayar Rom?", "pilihan": ["Nero", "Augustus Caesar", "Julius Caesar", "Brutus"], "jawapan": "Augustus Caesar"},
    {"soalan": "Apakah sistem sosial dalam tamadun Rom?", "pilihan": ["Kasta", "Feudal", "Patrician dan Plebeian", "Paderi dan rakyat"], "jawapan": "Patrician dan Plebeian"},
    {"soalan": "Apakah bahasa utama dalam tamadun Rom?", "pilihan": ["Latin", "Greek", "Sanskrit", "Ibrani"], "jawapan": "Latin"},
    {"soalan": "Siapakah tokoh perubatan terkenal dari tamadun Rom?", "pilihan": ["Galen", "Hippocrates", "Socrates", "Thales"], "jawapan": "Galen"},
    {"soalan": "Apakah kepercayaan utama masyarakat Rom?", "pilihan": ["Monoteisme", "Animisme", "Politeisme", "Atheisme"], "jawapan": "Politeisme"},
    {"soalan": "Sistem demokrasi di Athens digelar sebagai...", "pilihan": ["Demokrasi langsung", "Demokrasi berparlimen", "Monarki berperlembagaan", "Republik demokratik"], "jawapan": "Demokrasi langsung"},
    {"soalan": "Apakah peranan agora dalam masyarakat Yunani?", "pilihan": ["Tempat pertanian", "Pasar dan perhimpunan", "Kawasan sukan", "Kuil"], "jawapan": "Pasar dan perhimpunan"},
    {"soalan": "Antara berikut, manakah seni bina Yunani?", "pilihan": ["Pantheon", "Colosseum", "Parthenon", "Aqueduct"], "jawapan": "Parthenon"},
    {"soalan": "Apakah bidang utama yang dikaji oleh Aristotle?", "pilihan": ["Astronomi", "Falsafah dan Sains", "Perubatan", "Undang-undang"], "jawapan": "Falsafah dan Sains"},
    {"soalan": "Sparta mengamalkan pemerintahan jenis apa?", "pilihan": ["Demokrasi", "Republik", "Oligarki", "Monarki berperlembagaan"], "jawapan": "Oligarki"},
    {"soalan": "Salah satu sebab kejatuhan Empayar Rom ialah...", "pilihan": ["Serangan orang barbar", "Letusan gunung berapi", "Kejatuhan harga emas", "Kebuluran"], "jawapan": "Serangan orang barbar"},
    {"soalan": "Teater merupakan satu bentuk hiburan penting di...", "pilihan": ["Athens", "Sparta", "Delphi", "Pompeii"], "jawapan": "Athens"},
    {"soalan": "Siapakah guru kepada Alexander the Great?", "pilihan": ["Plato", "Aristotle", "Socrates", "Galen"], "jawapan": "Aristotle"},
    {"soalan": "Tamadun Yunani dan Rom berkembang di benua...", "pilihan": ["Asia", "Eropah", "Afrika", "Amerika"], "jawapan": "Eropah"},
    {"soalan": "Manakah antara berikut bukan tamadun awal di Eropah?", "pilihan": ["Rom", "Yunani", "Mesir", "Sparta"], "jawapan": "Mesir"},
    {"soalan": "Siapakah yang membunuh Julius Caesar?", "pilihan": ["Augustus", "Brutus", "Socrates", "Pompey"], "jawapan": "Brutus"},
    {"soalan": "Apakah nama arena pertarungan di Rom?", "pilihan": ["Stadium", "Parthenon", "Colosseum", "Agora"], "jawapan": "Colosseum"},
    {"soalan": "Apakah ciri utama seni bina Rom?", "pilihan": ["Tiang batu gaya Doric", "Gerbang dan kubah", "Kaca berwarna", "Ziggurat"], "jawapan": "Gerbang dan kubah"},
    {"soalan": "Tamadun Yunani menyumbang kepada perkembangan sistem...", "pilihan": ["Kasta", "Demokrasi", "Sosialis", "Komunis"], "jawapan": "Demokrasi"}
  ],
  'Bab 7': [
    {"soalan": "Apakah nama tamadun awal yang berkembang di Lembah Sungai Indus?", "pilihan": ["Mohenjo-Daro", "Gupta", "Maurya", "Qin"], "jawapan": "Mohenjo-Daro"},
    {"soalan": "Siapakah pengasas Empayar Maurya di India?", "pilihan": ["Asoka", "Chandragupta Maurya", "Harsha", "Samudragupta"], "jawapan": "Chandragupta Maurya"},
    {"soalan": "Apakah agama yang disebarkan oleh Raja Asoka?", "pilihan": ["Hindu", "Islam", "Buddha", "Jain"], "jawapan": "Buddha"},
    {"soalan": "Apakah sistem kasta dalam masyarakat India dikenali sebagai?", "pilihan": ["Varna", "Jati", "Veda", "Karma"], "jawapan": "Varna"},
    {"soalan": "Apakah kitab suci utama agama Hindu?", "pilihan": ["Quran", "Bible", "Veda", "Tripitaka"], "jawapan": "Veda"},
    {"soalan": "Tamadun India berkembang di lembah sungai apa?", "pilihan": ["Sungai Nil", "Sungai Gangga", "Sungai Tigris", "Sungai Mekong"], "jawapan": "Sungai Gangga"},
    {"soalan": "Apakah sumbangan utama tamadun India dalam bidang matematik?", "pilihan": ["Algebra", "Nombor sifar", "Geometri Euclid", "Kalkulus"], "jawapan": "Nombor sifar"},
    {"soalan": "Apakah sistem tulisan yang digunakan oleh tamadun awal India?", "pilihan": ["Cuneiform", "Hieroglif", "Brahmi", "Kanji"], "jawapan": "Brahmi"},
    {"soalan": "Apakah ciri utama seni bina India semasa zaman Maurya?", "pilihan": ["Pagoda", "Stupa", "Ziggurat", "Menara batu"], "jawapan": "Stupa"},
    {"soalan": "Apakah karya epik India yang terkenal?", "pilihan": ["Iliad", "Mahabharata", "Beowulf", "Aeneid"], "jawapan": "Mahabharata"},
    {"soalan": "Apakah nama dinasti yang menyatukan China buat kali pertama?", "pilihan": ["Tang", "Han", "Qin", "Zhou"], "jawapan": "Qin"},
    {"soalan": "Siapakah maharaja pertama Dinasti Qin?", "pilihan": ["Liu Bang", "Qin Shi Huang", "Wu Ti", "Confucius"], "jawapan": "Qin Shi Huang"},
    {"soalan": "Apakah sistem pemerintahan yang diamalkan oleh Dinasti Qin?", "pilihan": ["Demokrasi", "Falsafah Taoisme", "Legalism", "Feudalisme"], "jawapan": "Legalism"},
    {"soalan": "Apakah nama tembok yang dibina untuk pertahanan China?", "pilihan": ["Tembok Berlin", "Tembok Besar China", "Tembok Asoka", "Tembok Agung"], "jawapan": "Tembok Besar China"},
    {"soalan": "Apakah sumbangan utama Dinasti Han dalam bidang pendidikan?", "pilihan": ["Akademi Confucius", "Sekolah Tao", "Universiti Awam", "Institut Bahasa"], "jawapan": "Akademi Confucius"},
    {"soalan": "Apakah ajaran utama Confucius?", "pilihan": ["Karma", "Kesederhanaan", "Etika dan moral", "Kepercayaan kepada dewa-dewa"], "jawapan": "Etika dan moral"},
    {"soalan": "Apakah tulisan utama masyarakat China kuno?", "pilihan": ["Brahmi", "Cuneiform", "Hieroglif", "Hanzi"], "jawapan": "Hanzi"},
    {"soalan": "Siapakah tokoh falsafah terkenal dari China?", "pilihan": ["Laozi", "Confucius", "Mencius", "Semua jawapan betul"], "jawapan": "Semua jawapan betul"},
    {"soalan": "Apakah bahan utama yang digunakan oleh China untuk menulis?", "pilihan": ["Kertas", "Papirus", "Batu", "Daun"], "jawapan": "Kertas"},
    {"soalan": "Siapakah yang mencipta sistem perundangan di zaman Qin?", "pilihan": ["Qin Shi Huang", "Li Si", "Wu Ti", "Liu Bang"], "jawapan": "Li Si"},
    {"soalan": "Apakah sistem pentadbiran yang diamalkan dalam Dinasti Han?", "pilihan": ["Feudalisme", "Sistem birokrasi", "Demokrasi", "Autokrasi"], "jawapan": "Sistem birokrasi"},
    {"soalan": "Apakah perdagangan terkenal antara China dan dunia luar?", "pilihan": ["Perdagangan rempah", "Jalan Sutera", "Jalan Laut", "Laluan India"], "jawapan": "Jalan Sutera"},
    {"soalan": "Apakah pencapaian China dalam bidang perubatan?", "pilihan": ["Pembedahan moden", "Herba dan akupunktur", "Sains DNA", "Penemuan insulin"], "jawapan": "Herba dan akupunktur"},
    {"soalan": "Apakah tujuan utama Tembok Besar China dibina?", "pilihan": ["Sempadan negara", "Pertanian", "Pertahanan", "Perdagangan"], "jawapan": "Pertahanan"},
    {"soalan": "Manakah antara berikut adalah pencapaian teknologi tamadun China?", "pilihan": ["Jam matahari", "Kertas dan kompas", "Pisau batu", "Menara api"], "jawapan": "Kertas dan kompas"},
    {"soalan": "Apakah dasar pemerintahan Dinasti Qin terhadap rakyat?", "pilihan": ["Kebebasan beragama", "Keadilan sosial", "Pemerintahan keras", "Pilihan raya"], "jawapan": "Pemerintahan keras"},
    {"soalan": "Apakah nama ajaran yang menekankan keharmonian dengan alam?", "pilihan": ["Buddha", "Hindu", "Taoisme", "Legalism"], "jawapan": "Taoisme"},
    {"soalan": "Dinasti Han terkenal dengan sistem...", "pilihan": ["Demokrasi", "Sistem perhambaan", "Peperiksaan perkhidmatan awam", "Monarki mutlak"], "jawapan": "Peperiksaan perkhidmatan awam"},
    {"soalan": "Sumbangan Dinasti Gupta kepada matematik ialah...", "pilihan": ["Geometri Euclid", "Nombor Arab", "Konsep sifar", "Algebra India"], "jawapan": "Konsep sifar"},
    {"soalan": "Apakah kesan peluasan empayar Maurya?", "pilihan": ["Penyatuan budaya India", "Penyebaran agama Buddha", "Peningkatan hubungan luar", "Semua jawapan betul"], "jawapan": "Semua jawapan betul"},
    {"soalan": "Apakah maksud konsep 'Mandat Syurga' dalam tamadun China?", "pilihan": ["Kuasa rakyat", "Hak raja yang diberi oleh syurga", "Kewajipan berperang", "Kehendak rakyat"], "jawapan": "Hak raja yang diberi oleh syurga"},
    {"soalan": "Mengapakah sistem kasta sukar diubah?", "pilihan": ["Ia fleksibel", "Ia berdasarkan agama", "Ia disokong oleh pemerintah", "Ia tidak dikenali umum"], "jawapan": "Ia berdasarkan agama"},
    {"soalan": "Apakah nama bandar penting dalam Tamadun India awal?", "pilihan": ["Beijing", "Mohenjo-Daro", "Xian", "Angkor Wat"], "jawapan": "Mohenjo-Daro"},
    {"soalan": "Apakah bentuk seni bina utama China kuno?", "pilihan": ["Stupa", "Pagoda", "Ziggurat", "Menara"], "jawapan": "Pagoda"},
    {"soalan": "Siapakah yang memerintah Dinasti Han semasa zaman kegemilangan?", "pilihan": ["Liu Bang", "Qin Shi Huang", "Wu Ti", "Sun Tzu"], "jawapan": "Wu Ti"},
    {"soalan": "Apakah alat muzik tradisional tamadun China?", "pilihan": ["Erhu", "Sitar", "Tabla", "Lyre"], "jawapan": "Erhu"},
    {"soalan": "Apakah maksud 'Samsara' dalam agama Hindu?", "pilihan": ["Kesedaran diri", "Kelahiran semula", "Kebaikan mutlak", "Pembalasan segera"], "jawapan": "Kelahiran semula"},
    {"soalan": "Apakah simbol kemakmuran dalam tamadun China?", "pilihan": ["Naga", "Harimau", "Ular", "Singa"], "jawapan": "Naga"},
    {"soalan": "Apakah alat penting dalam sistem ukur tamadun India?", "pilihan": ["Tali ukur", "Skala tetap", "Grid bandar", "Kayu pengukur"], "jawapan": "Grid bandar"},
    {"soalan": "Apakah tujuan utama ajaran Confucius?", "pilihan": ["Menguasai orang lain", "Keharmonian sosial", "Pemujaan dewa", "Perjuangan kelas"], "jawapan": "Keharmonian sosial"}
  ],
  'Bab 8': [
    {"soalan": "Apakah maksud tamadun dalam Islam?", "pilihan": ["Kehidupan moden", "Perkembangan sains", "Pembangunan jasmani dan rohani berlandaskan ajaran Islam", "Kemajuan dalam perdagangan"], "jawapan": "Pembangunan jasmani dan rohani berlandaskan ajaran Islam"},
    {"soalan": "Siapakah pengasas agama Islam?", "pilihan": ["Nabi Isa", "Nabi Ibrahim", "Nabi Musa", "Nabi Muhammad SAW"], "jawapan": "Nabi Muhammad SAW"},
    {"soalan": "Apakah kitab suci umat Islam?", "pilihan": ["Taurat", "Injil", "Zabur", "Al-Quran"], "jawapan": "Al-Quran"},
    {"soalan": "Di manakah tamadun Islam mula berkembang?", "pilihan": ["Madinah", "Mesir", "Mekah", "Baghdad"], "jawapan": "Mekah"},
    {"soalan": "Apakah nama kerajaan Islam pertama?", "pilihan": ["Khulafa al-Rasyidin", "Abbasiyah", "Umaiyah", "Mamluk"], "jawapan": "Khulafa al-Rasyidin"},
    {"soalan": "Bilakah kelahiran Nabi Muhammad SAW?", "pilihan": ["570M", "610M", "622M", "632M"], "jawapan": "570M"},
    {"soalan": "Apakah peristiwa penting yang berlaku pada tahun 622M?", "pilihan": ["Kelahiran Nabi", "Wafatnya Nabi", "Hijrah ke Madinah", "Perang Badar"], "jawapan": "Hijrah ke Madinah"},
    {"soalan": "Apakah sumbangan Khalifah Abu Bakar As-Siddiq?", "pilihan": ["Membangun sistem pentadbiran", "Mengumpulkan ayat al-Quran", "Membina masjid", "Menubuhkan sekolah"], "jawapan": "Mengumpulkan ayat al-Quran"},
    {"soalan": "Siapakah khalifah yang terkenal dengan keadilan dan perluasan wilayah?", "pilihan": ["Uthman bin Affan", "Umar bin al-Khattab", "Ali bin Abi Talib", "Abu Bakar As-Siddiq"], "jawapan": "Umar bin al-Khattab"},
    {"soalan": "Apakah sistem pentadbiran yang diperkenalkan oleh Tamadun Islam?", "pilihan": ["Demokrasi", "Monarki", "Khilafah", "Feudalisme"], "jawapan": "Khilafah"},
    {"soalan": "Apakah bidang ilmu yang berkembang pesat dalam Tamadun Islam?", "pilihan": ["Falsafah", "Sains", "Perubatan", "Semua jawapan di atas"], "jawapan": "Semua jawapan di atas"},
    {"soalan": "Siapakah tokoh terkenal dalam bidang perubatan Islam?", "pilihan": ["Al-Khwarizmi", "Al-Razi", "Al-Farabi", "Ibn Khaldun"], "jawapan": "Al-Razi"},
    {"soalan": "Apakah sumbangan Al-Khwarizmi?", "pilihan": ["Fizik", "Perubatan", "Matematik dan Algebra", "Sejarah"], "jawapan": "Matematik dan Algebra"},
    {"soalan": "Apakah nama universiti tertua dalam dunia Islam?", "pilihan": ["Universiti Al-Azhar", "Universiti Baghdad", "Universiti Cordoba", "Universiti Al-Qarawiyyin"], "jawapan": "Universiti Al-Qarawiyyin"},
    {"soalan": "Apakah bahasa utama dalam tamadun Islam?", "pilihan": ["Yunani", "Ibrani", "Arab", "Parsi"], "jawapan": "Arab"},
    {"soalan": "Apakah kesan penyebaran Islam terhadap masyarakat dunia?", "pilihan": ["Kemerosotan ilmu", "Kehancuran budaya", "Perpaduan dan kemajuan", "Peningkatan peperangan"], "jawapan": "Perpaduan dan kemajuan"},
    {"soalan": "Apakah bentuk seni bina Islam yang terkenal?", "pilihan": ["Menara jam", "Pagoda", "Masjid", "Gereja"], "jawapan": "Masjid"},
    {"soalan": "Apakah contoh masjid yang menjadi lambang seni bina Islam?", "pilihan": ["Masjid Biru", "Masjid Kristal", "Masjid Al-Aqsa", "Masjidilharam"], "jawapan": "Masjid Biru"},
    {"soalan": "Apakah seni tulisan dalam tamadun Islam?", "pilihan": ["Kaligrafi", "Hieroglif", "Piktogram", "Grafiti"], "jawapan": "Kaligrafi"},
    {"soalan": "Apakah sistem undang-undang Islam?", "pilihan": ["Sivil", "Kanun", "Syariah", "Kanon"], "jawapan": "Syariah"},
    {"soalan": "Apakah tujuan utama penyebaran dakwah Islamiah?", "pilihan": ["Kekayaan", "Kuasai dunia", "Sebarkan ajaran Islam", "Tujuan politik"], "jawapan": "Sebarkan ajaran Islam"},
    {"soalan": "Apakah alat navigasi yang dibangunkan oleh ilmuwan Islam?", "pilihan": ["Teleskop", "Kompas", "Astrolab", "Mikroskop"], "jawapan": "Astrolab"},
    {"soalan": "Apakah pusat keilmuan terkenal dalam Tamadun Islam?", "pilihan": ["Madrasah", "Universiti", "Bayt al-Hikmah", "Perpustakaan Negara"], "jawapan": "Bayt al-Hikmah"},
    {"soalan": "Apakah maksud jihad dalam Islam?", "pilihan": ["Perang menentang orang bukan Islam", "Usaha sungguh-sungguh menegakkan agama Islam", "Menawan wilayah", "Menegakkan kuasa politik"], "jawapan": "Usaha sungguh-sungguh menegakkan agama Islam"},
    {"soalan": "Apakah nilai murni yang diterapkan dalam tamadun Islam?", "pilihan": ["Keberanian", "Kebebasan mutlak", "Amanah dan keadilan", "Paksaan"], "jawapan": "Amanah dan keadilan"},
    {"soalan": "Apakah sistem ekonomi dalam tamadun Islam?", "pilihan": ["Sosialis", "Kapitalis", "Berasaskan zakat dan muamalat", "Barter"], "jawapan": "Berasaskan zakat dan muamalat"},
    {"soalan": "Siapakah tokoh sejarah Islam yang menulis 'Muqaddimah'?", "pilihan": ["Al-Khwarizmi", "Ibn Sina", "Ibn Khaldun", "Al-Farabi"], "jawapan": "Ibn Khaldun"},
    {"soalan": "Apakah maksud tamadun menurut Ibn Khaldun?", "pilihan": ["Kemajuan material", "Peradaban manusia", "Kekuatan ketenteraan", "Kejayaan perdagangan"], "jawapan": "Peradaban manusia"},
    {"soalan": "Apakah contoh sumbangan Islam dalam bidang seni?", "pilihan": ["Patung", "Lukisan wajah", "Kaligrafi dan seni bina", "Tarian"], "jawapan": "Kaligrafi dan seni bina"},
    {"soalan": "Di manakah terletaknya Tamadun Islam di Andalusia?", "pilihan": ["Iran", "India", "Sepanyol", "Turki"], "jawapan": "Sepanyol"},
    {"soalan": "Apakah sistem pendidikan dalam tamadun Islam?", "pilihan": ["Berteraskan falsafah Yunani", "Disusun oleh pemerintah", "Berlandaskan ajaran Al-Quran dan Hadis", "Tanpa sistem formal"], "jawapan": "Berlandaskan ajaran Al-Quran dan Hadis"},
    {"soalan": "Apakah nama tokoh Islam yang dikenali sebagai 'Bapa Perubatan Islam'?", "pilihan": ["Al-Razi", "Ibn Sina", "Al-Farabi", "Ibn Khaldun"], "jawapan": "Ibn Sina"},
    {"soalan": "Apakah bidang yang diceburi oleh Al-Farabi?", "pilihan": ["Sejarah", "Matematik", "Falsafah", "Geografi"], "jawapan": "Falsafah"},
    {"soalan": "Apakah bentuk kerajaan dalam tamadun Islam?", "pilihan": ["Demokrasi", "Kesultanan", "Khilafah", "Empayar"], "jawapan": "Khilafah"},
    {"soalan": "Apakah sumbangan Islam terhadap matematik?", "pilihan": ["Logaritma", "Algebra", "Geometri Euclid", "Kalkulus"], "jawapan": "Algebra"},
    {"soalan": "Apakah peranan masjid dalam masyarakat Islam?", "pilihan": ["Tempat pelancongan", "Pusat kebudayaan", "Tempat sembahyang sahaja", "Pusat ibadat dan pembelajaran"], "jawapan": "Pusat ibadat dan pembelajaran"},
    {"soalan": "Apakah hasil kesusasteraan Islam yang penting?", "pilihan": ["Tajul Muluk", "Muqaddimah", "Suluk", "Cerita Panji"], "jawapan": "Muqaddimah"},
    {"soalan": "Apakah ciri tamadun Islam?", "pilihan": ["Berpusatkan raja", "Berteraskan akidah dan syariah", "Berasaskan perang", "Paksaan agama"], "jawapan": "Berteraskan akidah dan syariah"},
    {"soalan": "Bagaimanakah tamadun Islam menyebarkan ilmu?", "pilihan": ["Melalui penjajahan", "Melalui penulisan, terjemahan, dan pengajaran", "Melalui peperangan", "Melalui seni halus"], "jawapan": "Melalui penulisan, terjemahan, dan pengajaran"},
    {"soalan": "Apakah tokoh Islam yang mengkaji bintang dan planet?", "pilihan": ["Al-Farabi", "Al-Biruni", "Ibn Khaldun", "Ibn Sina"], "jawapan": "Al-Biruni"}
  ],
};
